const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const puzzles={
 sokoban:{label:'Sokoban',description:'Plan crate pushes. One bad corner can end the run.',levels:[
  {id:'s1',name:'Warm-up',title:'One crate.<br>One promise.',kicker:'LOGIC LAB · LEVEL 01',map:['#####','# . #','# $ #','# @ #','#####']},
  {id:'s2',name:'Two crates',title:'Two crates.<br>One clean route.',kicker:'LOGIC LAB · LEVEL 02',map:['########','# .  . #','# $  $ #','#  @   #','########']},
  {id:'s3',name:'Three bay',title:'Three bays.<br>No wasted pushes.',kicker:'LOGIC LAB · ADVANCED',map:['#########','# . . . #','# $ $ $ #','#   @   #','#########']},
  {id:'s4',name:'Switchback',title:'A tighter<br>warehouse.',kicker:'LOGIC LAB · HARD',map:['#########','# .   . #','# $ # $ #','#   @   #','#########']},
  {id:'s5',name:'Microban 02',title:'A compact<br>two-crate proof.',kicker:'MICROBAN · PUBLIC-DOMAIN SET',map:['######','#    #','# #@ #','# $* #','# .* #','#    #','######']},
  {id:'s6',name:'Reference warehouse',title:'A warehouse<br>with room to plan.',kicker:'AGENT ARCADE · IMAGE-INSPIRED',map:['###########','# . . .   #','# $ $ $   #','#   @ #   #','###########']},
  {id:'s7',name:'Five-lane push',title:'Four crates.<br>One escape route.',kicker:'LOGIC LAB · EXPERT',map:['###########','# . . . . #','# $ $ $ $ #','#    @    #','###########']},
  {id:'s9',name:'Microban 31',title:'Split lanes.<br>No free pushes.',kicker:'MICROBAN · PUBLIC-DOMAIN SET',map:['  ####',' ##  #','##@$.##','# $$  #','# . . #','###   #','  #####']},
  {id:'s10',name:'Microban 38',title:'Tight corners.<br>Long recovery.',kicker:'MICROBAN · PUBLIC-DOMAIN SET',map:['##########','#        #','# ##.### #','# # $$ . #','# . @$## #','#####    #','    ######']},
  {id:'s11',name:'Microban 47',title:'A hard turn.<br>Three crates.',kicker:'MICROBAN · PUBLIC-DOMAIN SET',map:['  #######','###     #','# $ $   #','# ### #####','# @ . .   #','#   ###   #','##### #####']}
 ]},
 maze:{label:'Maze',description:'Navigate to the green exit. The maze exposes pure path planning.',levels:[
  {id:'m1',name:'Maze 01',title:'Maze 01.<br>Route planning.',kicker:'MAZE · LEVEL 01',map:['#########','#@     ##','# ### # ##','#   # #  #','### # ## #','#   #  . #','#########']},
  {id:'m2',name:'Maze 02',title:'Maze 02.<br>Crossroads.',kicker:'MAZE · LEVEL 02',map:['###########','#@ #      #','#  # #### #','## # #    #','#  # # ####','# ## #    #','#    ####.#','###########']},
  {id:'m3',name:'Maze 03',title:'Maze 03.<br>Long route.',kicker:'MAZE · HARD',map:['###########','#@        #','######### #','#       # #','# ##### # #','# #   # # #','# # # ### #','#   #    .#','###########']},
  {id:'m4',name:'Expert weave',title:'Every fork<br>costs time.',kicker:'MAZEPRINT · EXPERT 20 × 20',map:['#####################','#@    #       #     #','##### # ##### # ### #','#   # # #   # # #   #','# # # # # # # # # ###','# #   # # # #   #   #','# ##### # # ##### # #','#     # # #     # # #','##### # # ##### # # #','#   # # #     # # # #','# # # ####### # # # #','# # #       # # # # #','# # ####### # # # # #','# #       # # # # # #','# ####### # # # # # #','#       # # # # # # #','####### # # # # # # #','#     # #   # # #   #','# ### ####### # ### #','#   #         #    .#','#####################']},
  {id:'m5',name:'Dead-end garden',title:'A dense maze.<br>Zero shortcuts.',kicker:'MAZEPRINT · HARD 21 × 21',map:['#####################','#@#       #         #','# # ##### # ####### #','# # #   # # #     # #','# # # # # # # ### # #','#   # # #   # # # # #','##### # ##### # # # #','#     #     # # #   #','# ######### # # #####','# #       # # #     #','# # ##### # # ##### #','# # #   # # #     # #','# # # # # # ##### # #','# # # # # #     # # #','# # # # # ##### # # #','# #   # #     # #   #','# ##### ##### # #####','#     #     # #     #','##### # ### # ##### #','#       #   #      .#','#####################']},
  {id:'m6',name:'Spiral archive',title:'The exit is near.<br>The route is not.',kicker:'MAZEPRINT · EXPERT 21 × 21',map:['#####################','#@                  #','# ################# #','# #               # #','# # ############# # #','# # #           # # #','# # # ######### # # #','# # # #       # # # #','# # # # ##### # # # #','# # # # #   # # # # #','# # # # # # # # # # #','# # # # # # # # # # #','# # # # # # ### # # #','# # # # # #     # # #','# # # # # ####### # #','# # # # #         # #','# # # # ########### #','# # # #             #','# # # ###############','#   #                .','#####################']}
 ]},
 klotski:{label:'Klotski',description:'Every tile has a number. Commands are explicit: 1R means slide box 1 right.',levels:[
  {id:'k1',name:'Beginner 2',title:'Slide the blue<br>block home.',kicker:'KLOTSKI · IMAGE-INSPIRED · BEGINNER',cols:6,rows:6,exitRow:2,pieces:[{id:'1',x:0,y:2,w:2,h:1,target:1},{id:'2',x:2,y:2,w:1,h:2},{id:'3',x:4,y:2,w:1,h:2},{id:'4',x:0,y:0,w:2,h:1},{id:'5',x:0,y:5,w:2,h:1},{id:'6',x:3,y:5,w:2,h:1}]},
  {id:'k2',name:'Advanced 2',title:'Move the gates.<br>Then escape.',kicker:'KLOTSKI · IMAGE-INSPIRED · ADVANCED',cols:6,rows:6,exitRow:2,pieces:[{id:'1',x:0,y:2,w:2,h:1,target:1},{id:'2',x:2,y:1,w:1,h:3},{id:'3',x:4,y:1,w:1,h:3},{id:'4',x:0,y:0,w:2,h:1},{id:'5',x:0,y:5,w:2,h:1},{id:'6',x:3,y:0,w:1,h:2},{id:'7',x:5,y:4,w:1,h:2}]},
  {id:'k3',name:'Advanced 3',title:'Clear the lower<br>relay first.',kicker:'KLOTSKI · IMAGE-INSPIRED · ADVANCED',cols:6,rows:6,exitRow:2,pieces:[{id:'1',x:0,y:2,w:2,h:1,target:1},{id:'2',x:2,y:1,w:1,h:3},{id:'3',x:4,y:1,w:1,h:3},{id:'4',x:1,y:5,w:2,h:1},{id:'5',x:0,y:0,w:2,h:1},{id:'6',x:3,y:0,w:1,h:2},{id:'7',x:5,y:4,w:1,h:2}]},
  {id:'k4',name:'Advanced 4',title:'Clear every<br>long lane.',kicker:'KLOTSKI · IMAGE-INSPIRED · ADVANCED',cols:6,rows:6,exitRow:2,pieces:[{id:'1',x:0,y:2,w:2,h:1,target:1},{id:'2',x:2,y:1,w:1,h:2},{id:'3',x:4,y:2,w:1,h:2},{id:'4',x:0,y:0,w:2,h:1},{id:'5',x:0,y:5,w:2,h:1},{id:'6',x:3,y:0,w:1,h:2},{id:'7',x:3,y:5,w:2,h:1},{id:'8',x:5,y:4,w:1,h:2}]},
  {id:'k5',name:'Gallery relay',title:'A compact<br>numbered route.',kicker:'KLOTSKI · CLASSIC LONG-BLOCK RULES',cols:6,rows:6,exitRow:2,pieces:[{id:'1',x:0,y:2,w:2,h:1,target:1},{id:'2',x:2,y:2,w:1,h:2},{id:'3',x:4,y:2,w:1,h:2},{id:'4',x:0,y:0,w:2,h:1},{id:'5',x:0,y:5,w:2,h:1},{id:'6',x:3,y:0,w:1,h:2},{id:'7',x:3,y:5,w:2,h:1},{id:'8',x:5,y:0,w:1,h:2},{id:'9',x:5,y:4,w:1,h:2}]}
 ]},
 jigsaw:{label:'Jigsaw',description:'Mouse-first visual puzzles. Try the same board with a reference image or vision-only.',levels:[
  {id:'j1',name:'Cat 9-piece',title:'Nine pieces.<br>Cat portrait.',kicker:'JIGSAW · 3 × 3',n:3,art:"url('/assets/cat.jpg')"},
  {id:'j2',name:'Orbit 9-piece',title:'Nine pieces.<br>Find orbit.',kicker:'JIGSAW · 3 × 3',n:3,art:'radial-gradient(circle at 50% 50%,#f8c500 0 13%,#ff631d 14% 20%,transparent 21%),linear-gradient(55deg,#352c78,#69c0e1)'},
  {id:'j3',name:'Cat 16-piece',title:'Sixteen pieces.<br>Cat portrait.',kicker:'JIGSAW · 4 × 4',n:4,art:"url('/assets/cat.jpg')"},
  {id:'j4',name:'Night 16-piece',title:'Sixteen pieces.<br>Trust vision.',kicker:'JIGSAW · 4 × 4',n:4,art:'radial-gradient(circle at 70% 23%,#e7dd99 0 10%,transparent 11%),linear-gradient(135deg,#171e52,#8b4ca3 55%,#f49b60)'},
  {id:'j5',name:'Cat 25-piece',title:'Twenty-five<br>small clues.',kicker:'JIGSAW · HARD · 5 × 5',n:5,art:"url('/assets/cat.jpg')"},
  {id:'j6',name:'Signal 25-piece',title:'Find the pattern.<br>No easy edge.',kicker:'JIGSAW · HARD · 5 × 5',n:5,art:'radial-gradient(circle at 20% 22%,#ffe391 0 7%,transparent 8%),radial-gradient(circle at 78% 65%,#fa752e 0 9%,transparent 10%),linear-gradient(140deg,#122e52,#52c7bd 48%,#f2c15b)'},
  {id:'j7',name:'Cat 36-piece',title:'Thirty-six<br>visual decisions.',kicker:'JIGSAW · EXPERT · 6 × 6',n:6,art:"url('/assets/cat.jpg')"},
  {id:'j8',name:'Aurora 36-piece',title:'A dense field<br>of colour.',kicker:'JIGSAW · EXPERT · 6 × 6',n:6,art:'radial-gradient(circle at 70% 22%,#fff3a3 0 6%,transparent 7%),linear-gradient(155deg,#14214c 10%,#55c6c2 45%,#cf58b2 74%,#f7b64a)'}
 ]}
};
const modelDefaults={local:'Local deterministic solver',claude:'claude-sonnet-5',openai:'gpt-5.6-terra'};
const modelPresets={
 claude:[['claude-fable-5','Claude Fable 5 · frontier'],['claude-opus-4-8','Claude Opus 4.8 · deep'],['claude-sonnet-5','Claude Sonnet 5 · balanced'],['claude-haiku-4-5-20251001','Claude Haiku 4.5 · fast']],
 openai:[['gpt-5.6-sol','GPT-5.6 Sol · strongest'],['gpt-5.6-terra','GPT-5.6 Terra · balanced'],['gpt-5.6-luna','GPT-5.6 Luna · fast'],['gpt-5.4-mini','GPT-5.4 mini · economical']]
};
const runModeDetails={free:'The agent receives no route hints. It may observe, reason, delegate, and create temporary helpers, but must find its own strategy.',verify:'The agent may check a batch it proposed itself. The checker reports only whether that batch is legal; it never searches for a route.',assist:'The agent may explicitly request a local deterministic route. This is for demonstrations and comparison, not independent puzzle solving.'};
const runModeLabels={free:'Free agent',verify:'Action checker',assist:'Solver aid'};
let type='sokoban',levelId='s2',state,selectedPiece,selectedTile,workspaces=[{id:'main',name:'Main agent',status:'ready',parent:'Authoritative workspace'}],activeWorkspace='main',trace=[],isRunning=false,timer,modelChoice='local',modelId=modelDefaults.local,runMode='free',pickerType='sokoban',liveRun={timer:null,startedAt:0,events:[]},runGeneration=0,lastUsage=null;
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
const current=()=>puzzles[type],level=()=>current().levels.find(x=>x.id===levelId),pos=(x,y)=>`${x},${y}`;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2400)}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function log(label,text,kind='',meta={}){trace.push({label,text,kind,...meta});if($('#drawer').classList.contains('show'))renderDrawerContent()}
function normaliseMap(map){const width=Math.max(...map.map(row=>row.length));return map.map(row=>row.padEnd(width,'#'))}
function parseGrid(map){let player,goal;const goals=[],crates=[];const base=normaliseMap(map).map((r,y)=>[...r].map((c,x)=>{if('.+*'.includes(c)){goals.push([x,y]);goal=[x,y]}if('$*'.includes(c))crates.push([x,y]);if('@+'.includes(c))player=[x,y];return c==='#'?'#':' '}));if(!player)throw new Error('Puzzle map has no player start.');return{base,player,goal,goals,crates,steps:0,pushes:0,solved:false}}
function resetLiveRun(){clearInterval(liveRun.timer);liveRun={timer:null,startedAt:0,events:[]};$('#live-run-panel').hidden=true}
function elapsed(){let seconds=Math.max(0,Math.floor((Date.now()-liveRun.startedAt)/1000));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function renderLiveRun(){const panel=$('#live-run-panel');if(!liveRun.startedAt){panel.hidden=true;return}panel.hidden=false;$('#live-run-elapsed').textContent=elapsed();$('#live-run-title').textContent=liveRun.title||'Agent is working on the puzzle.';$('#live-run-detail').textContent=liveRun.detail||'Preparing the next safe step.';$('#live-run-cost').textContent=lastUsage?formatUsage(lastUsage):'cost pending';$('#live-run-events').innerHTML=liveRun.events.slice(-4).map((event,index)=>`<li class="${index===liveRun.events.slice(-4).length-1?'current':'done'}">${event}</li>`).join('')}
function beginLiveRun(title,detail){resetLiveRun();liveRun.startedAt=Date.now();liveRun.title=title;liveRun.detail=detail;liveRun.events=['Workspace opened'];liveRun.timer=setInterval(renderLiveRun,400);renderLiveRun()}
function updateLiveRun(title,detail,event){if(!liveRun.startedAt)return;liveRun.title=title;liveRun.detail=detail;if(event&&liveRun.events.at(-1)!==event)liveRun.events.push(event);renderLiveRun()}
function finishLiveRun(title,detail){if(!liveRun.startedAt)return;updateLiveRun(title,detail,'Run complete');clearInterval(liveRun.timer);liveRun.timer=null;setTimeout(()=>{$('#live-run-panel').hidden=true},7000)}
function friendlyAction(direction,index,total){return `Move ${String(index+1).padStart(2,'0')}/${String(total).padStart(2,'0')} · ${({up:'↑ Up',down:'↓ Down',left:'← Left',right:'→ Right'})[direction]||direction}`}
function briefTrace(text,limit=180){const clean=String(text||'').replace(/[#*_`]/g,'').replace(/\s+/g,' ').trim();return clean.length>limit?`${clean.slice(0,limit-1).trim()}…`:clean}
function traceTone(entry){const label=entry.label||'';if(label==='PLAN UPDATE'||label==='DECISION')return'plan';if(label.includes('BRANCH')||label.includes('EXPLORER')||label==='SPAWN')return'branch';if(label.includes('HELPER')||label==='WORKSPACE')return'helper';if(label.includes('ACTION')||label==='BATCH'||label==='EXECUTION')return'action';if(label==='RESULT'||label==='RUN COMPLETE')return'result';if(label==='OBSERVATION')return'observe';return entry.kind==='report'?'report':'neutral'}
function traceTitle(entry){return({
  'RUN START':'Run connected','OBSERVATION':'Board observation','PLAN UPDATE':'Plan checkpoint','ACTION PLAN':'Action batch','ACTION CHECK':'Action check','BRANCH START':'Explorer dispatched','BRANCH REPORT':'Explorer report','EXPLORER LIMIT':'Explorer limit','HELPER FILE':'Helper drafted','HELPER RUN':'Helper executed','HELPER SKIPPED':'Helper skipped','WORKSPACE':'Workspace update','RUN COMPLETE':'Puzzle solved','RESULT':'Result','RUN ERROR':'Run needs attention','REPLAN':'Next decision requested','SOLVER AID':'Solver aid'
})[entry.label]||entry.label||'Update'}
function traceField(label,value){return value?`<div class="trace-field"><b>${escapeHtml(label)}</b><span>${escapeHtml(value)}</span></div>`:''}
function traceCard(entry,step,compact=false){const tone=traceTone(entry),fields=[];if(entry.explorer)fields.push(traceField('Explorer',entry.explorer));if(entry.observation)fields.push(traceField('Observed',entry.observation));if(entry.plan)fields.push(traceField('Plan',entry.plan));if(entry.reason)fields.push(traceField('Reason',entry.reason));if(entry.expected&&!compact)fields.push(traceField('Expected',entry.expected));if(entry.objective)fields.push(traceField('Question',entry.objective));if(entry.report)fields.push(traceField('Finding',entry.report));if(entry.actions?.length)fields.push(traceField('Actions',entry.actions.join(' · ')));if(entry.file)fields.push(traceField('File',entry.file));if(entry.output)fields.push(traceField(entry.status==='complete'?'Output':'Result',entry.output));if(entry.failure)fields.push(traceField('Check',entry.failure));const fallback=fields.length?'':`<p class="trace-summary">${escapeHtml(briefTrace(entry.text,compact?150:420))}</p>`;return`<article class="trace-item trace-${tone}"><div class="trace-head"><span class="trace-step">${String(step).padStart(2,'0')}</span><div><p class="trace-label">${escapeHtml(entry.label||'UPDATE')}</p><h3>${escapeHtml(traceTitle(entry))}</h3></div></div>${fields.length?`<div class="trace-fields">${fields.join('')}</div>`:fallback}</article>`}
function formatUsage(usage){if(!usage)return '—';const c=usage.estimatedCostUsd;return Number.isFinite(c)?`~$${c<.1?c.toFixed(4):c.toFixed(2)}`:'tokens tracked'}
function setUsage(usage){if(!usage)return;lastUsage=usage;$('#run-cost').textContent=formatUsage(usage);renderLiveRun()}
function resetRunContext(){trace=[];lastUsage=null;workspaces=[{id:'main',name:'Main agent',status:'ready',parent:'Authoritative workspace'}];activeWorkspace='main';$('#agent-count').textContent='1';$('#active-workspace').textContent='Main agent';$('#run-cost').textContent='—'}
function init(){runGeneration++;stop(true);resetLiveRun();resetRunContext();selectedPiece=null;selectedTile=null;const l=level();if(type==='sokoban')state=parseGrid(l.map);else if(type==='maze')state=parseGrid(l.map);else if(type==='klotski')state={pieces:structuredClone(l.pieces),cols:l.cols||6,rows:l.rows||6,exitRow:l.exitRow??2,steps:0,solved:false};else state={n:l.n,art:l.art,steps:0,solved:false,pieces:shuffle([...Array(l.n*l.n)].map((_,i)=>i)),placed:{},reference:true,history:[]};$('#puzzle-kicker').textContent=l.kicker;$('#arena-name').textContent=`${current().label} · ${l.name}`;$('#mode-copy').textContent=type==='jigsaw'?'Virtual mouse / vision':'Structured logic';$('#game-caption').textContent=type==='sokoban'?'Arrow keys move the keeper. Every crate must land on a target.':type==='maze'?'Arrow keys navigate to the green exit.':type==='klotski'?'Select a numbered long tile, then use arrows. Example: 2U. Every tile moves only along its long axis.':'Select a tile, then a destination. Click a placed tile to remove it.';$('#undo-piece-button').hidden=type!=='jigsaw';$('#step-count').textContent='00';$('#push-count').textContent='00';$('#metric-two').textContent=type==='maze'?'cells explored':type==='jigsaw'?'pieces placed':type==='klotski'?'slides':'pushes';$('#run-status').textContent='READY';$('#command-value').textContent='—';renderBoard();renderCards()}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function renderBoard(){if(type==='sokoban'||type==='maze')renderGrid();if(type==='klotski')renderKlotski();if(type==='jigsaw')renderJigsaw()}
function renderGrid(){const rows=state.base.length,cols=state.base[0].length,goals=new Set((type==='sokoban'?state.goals:[state.goal]).map(p=>pos(...p))),crates=new Set((state.crates||[]).map(p=>pos(...p)));$('#game-stage').innerHTML=`<div class="grid-board" style="--cols:${cols};--rows:${rows}">${state.base.map((r,y)=>r.map((c,x)=>{let k=pos(x,y),g=goals.has(k);return`<div class="grid-cell ${c==='#'?'wall':''} ${g?'goal':''}">${crates.has(k)?`<i class="crate ${g?'good':''}"></i>`:''}${k===pos(...state.player)?`<i class="${type==='maze'?'maze-player':'player'}"></i>`:''}${type==='maze'&&g?'<i class="maze-goal"></i>':''}</div>`}).join('')).join('')}</div>`}
function wall(s,x,y){return y<0||y>=s.base.length||x<0||x>=s.base[0].length||s.base[y][x]==='#'}function crate(s,x,y){return s.crates.findIndex(c=>c[0]===x&&c[1]===y)}
function move(dir,agent=false){if(state.solved||(isRunning&&!agent)||type==='jigsaw'||type==='klotski')return false;let [dx,dy]=dirs[dir],[x,y]=state.player,nx=x+dx,ny=y+dy;if(wall(state,nx,ny)){if(!agent)log('REJECTED','Wall blocks that action.');return false}if(type==='sokoban'){let ci=crate(state,nx,ny);if(ci>=0){let bx=nx+dx,by=ny+dy;if(wall(state,bx,by)||crate(state,bx,by)>=0){if(!agent)log('REJECTED','The crate cannot be pushed there.');return false}state.crates[ci]=[bx,by];state.pushes++}}state.player=[nx,ny];state.steps++;$('#step-count').textContent=String(state.steps).padStart(2,'0');$('#push-count').textContent=String(state.pushes||state.steps).padStart(2,'0');$('#command-value').textContent=dir[0].toUpperCase();renderGrid();if(!agent)log('MANUAL ACTION',`Moved ${dir}.`,'action');let done=type==='maze'?pos(...state.player)===pos(...state.goal):state.goals.every(g=>crate(state,...g)>=0);if(done)complete();return true}
function renderKlotski(){$('#game-stage').innerHTML=`<div class="klotski-board" style="--cols:${state.cols};--rows:${state.rows};--exit-row:${state.exitRow}"><span class="exit">»</span>${state.pieces.map(p=>`<button class="k-piece ${p.target?'target':''} ${selectedPiece===p.id?'selected':''}" data-k="${p.id}" style="--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}">${p.id}</button>`).join('')}</div>`;$$('[data-k]').forEach(b=>b.onclick=()=>{selectedPiece=b.dataset.k;renderKlotski();log('SELECTION',`Selected box ${selectedPiece}.`)} )}
function occupiedK(pieces,except){const taken=new Set();pieces.filter(q=>q!==except).forEach(q=>{for(let y=q.y;y<q.y+q.h;y++)for(let x=q.x;x<q.x+q.w;x++)taken.add(pos(x,y))});return taken}
function canMoveK(env,p,dir){if(!p||!dirs[dir])return false;const horizontal=p.w>p.h;if((horizontal&&['up','down'].includes(dir))||(!horizontal&&['left','right'].includes(dir)))return false;const[dx,dy]=dirs[dir],nx=p.x+dx,ny=p.y+dy,taken=occupiedK(env.pieces,p);for(let y=ny;y<ny+p.h;y++)for(let x=nx;x<nx+p.w;x++)if(x<0||x>=env.cols||y<0||y>=env.rows||taken.has(pos(x,y)))return false;return true}
function moveK(dir,agent=false,pieceId){if(state.solved||(isRunning&&!agent))return false;let p=state.pieces.find(x=>x.id===(pieceId||selectedPiece))||state.pieces.find(x=>x.target);if(!p)return false;if(!canMoveK(state,p,dir)){if(!agent)log('REJECTED',`Command ${p.id}${dir[0].toUpperCase()} is blocked or off-axis.`);return false}const[dx,dy]=dirs[dir];p.x+=dx;p.y+=dy;state.steps++;$('#step-count').textContent=String(state.steps).padStart(2,'0');$('#push-count').textContent=String(state.steps).padStart(2,'0');$('#command-value').textContent=`${p.id}${dir[0].toUpperCase()}`;renderKlotski();if(!agent)log('COMMAND',`Applied ${p.id}${dir[0].toUpperCase()}.`,'action');if(p.target&&p.y===state.exitRow&&p.x===state.cols-p.w)complete();return true}
function artStyle(i){let n=state.n,x=i%n,y=Math.floor(i/n);return`--art:${state.art};--n:${n};--x:${x};--y:${y}`}
function renderJigsaw(){let n=state.n;let placed=Object.entries(state.placed);$('#game-stage').innerHTML=`<div class="jigsaw-wrap ${n>=5?'dense':''} ${state.reference?'':'hidden-ref'}"><div class="jigsaw-board" style="--n:${n}">${[...Array(n*n)].map((_,slot)=>{let piece=state.placed[slot],occupied=piece!==undefined;return`<button aria-label="${occupied?`Remove tile ${piece+1} from board cell ${slot+1}`:`Board cell ${slot+1}`}" class="j-slot ${occupied?'placed':''}" data-slot="${slot}" ${occupied?`style="${artStyle(piece)}"`:''}></button>`}).join('')}</div><div><div class="reference" style="background:${state.art}"></div><div class="ref-label">reference${state.reference?'':' hidden'}</div><div class="j-tray">${state.pieces.filter(i=>!placed.some(([,p])=>+p===i)).map(i=>`<button aria-label="Jigsaw tile ${i+1}" class="j-piece ${selectedTile===i?'selected':''}" data-tile="${i}" style="${artStyle(i)}"></button>`).join('')}</div></div></div>`;$$('[data-tile]').forEach(b=>b.onclick=()=>{selectedTile=+b.dataset.tile;renderJigsaw();log('TILE SELECTED',`Tile ${selectedTile+1} is ready to place.`)});$$('[data-slot]').forEach(b=>b.onclick=()=>placeTile(+b.dataset.slot))}
function saveJigsawHistory(){state.history.push(structuredClone(state.placed));if(state.history.length>50)state.history.shift()}
function syncJigsawMetrics(){const placed=Object.keys(state.placed).length;$('#step-count').textContent=String(state.steps).padStart(2,'0');$('#push-count').textContent=String(placed).padStart(2,'0')}
function removeTile(slot){let piece=state.placed[slot];if(piece===undefined)return;saveJigsawHistory();delete state.placed[slot];selectedTile=null;$('#command-value').textContent=`REMOVE ${slot+1}`;syncJigsawMetrics();log('TILE REMOVED',`Tile ${piece+1} returned to the tray from cell ${slot+1}.`,'action');renderJigsaw();toast('Tile returned to the tray.')}
function undoJigsaw(){if(type!=='jigsaw'||!state.history.length){toast('Nothing to undo yet.');return}state.placed=state.history.pop();selectedTile=null;$('#command-value').textContent='UNDO';syncJigsawMetrics();log('UNDO',`Restored the previous jigsaw arrangement.`,'action');renderJigsaw()}
function placeTile(slot){if(state.placed[slot]!==undefined){removeTile(slot);return}if(selectedTile===undefined||selectedTile===null){toast('Select a tile first.');return}saveJigsawHistory();state.placed[slot]=selectedTile;state.steps++;syncJigsawMetrics();$('#command-value').textContent=`CLICK ${slot+1}`;log('TILE PLACED',`Tile ${selectedTile+1} placed in cell ${slot+1}.`,'action');selectedTile=null;renderJigsaw();if(Object.keys(state.placed).length===state.n*state.n&&Object.entries(state.placed).every(([s,p])=>+s===+p))complete()}
function encode(s){return`${s.player.join(',')}|${s.crates.map(c=>c.join(',')).sort().join(';')}`}
function solveSoko(initial){let q=[structuredClone(initial)],seen=new Set([encode(initial)]),count=0;while(q.length&&count++<70000){let s=q.shift();if(s.goals.every(g=>crate(s,...g)>=0))return s.path||[];for(let[d,[dx,dy]]of Object.entries(dirs)){let n=structuredClone(s),[x,y]=n.player,nx=x+dx,ny=y+dy;if(wall(n,nx,ny))continue;let ci=crate(n,nx,ny);if(ci>=0){let bx=nx+dx,by=ny+dy;if(wall(n,bx,by)||crate(n,bx,by)>=0)continue;n.crates[ci]=[bx,by]}n.player=[nx,ny];n.path=[...(s.path||[]),d];let k=encode(n);if(!seen.has(k)){seen.add(k);q.push(n)}}}return null}
function solveMaze(initial){let q=[{p:initial.player,path:[]}],seen=new Set([pos(...initial.player)]);while(q.length){let z=q.shift();if(pos(...z.p)===pos(...initial.goal))return z.path;for(let[d,[dx,dy]]of Object.entries(dirs)){let n=[z.p[0]+dx,z.p[1]+dy],k=pos(...n);if(!wall(initial,...n)&&!seen.has(k)){seen.add(k);q.push({p:n,path:[...z.path,d]})}}}return null}
function encodeKlotski(s){return s.pieces.map(p=>`${p.id}:${p.x},${p.y}`).join('|')}
function solveKlotski(initial){const queue=[structuredClone(initial)],seen=new Set([encodeKlotski(initial)]);let examined=0;while(queue.length&&examined++<120000){const currentState=queue.shift(),target=currentState.pieces.find(p=>p.target);if(target&&target.y===currentState.exitRow&&target.x===currentState.cols-target.w)return currentState.path||[];for(const piece of currentState.pieces)for(const direction of Object.keys(dirs)){if(!canMoveK(currentState,piece,direction))continue;const next=structuredClone(currentState),moving=next.pieces.find(p=>p.id===piece.id),[dx,dy]=dirs[direction];moving.x+=dx;moving.y+=dy;next.path=[...(currentState.path||[]),{id:piece.id,direction}];const code=encodeKlotski(next);if(!seen.has(code)){seen.add(code);queue.push(next)}}}return null}
function run(){
  if(isRunning||state.solved)return;
  if(type==='jigsaw'){
    if(!state.reference){toast('A vision-only run needs a board-observation tool before it can place tiles.');log('VISION MODE','Reference withheld; no placement was guessed.','report');return}
    let open=[...Array(state.n*state.n)].map((_,i)=>i).filter(i=>state.placed[i]===undefined);isRunning=true;$('#run-status').textContent='RUNNING';beginLiveRun('Local visual agent is assembling the board.','Matching reference tiles to their destination cells.');
    let i=0;const tick=()=>{if(!isRunning)return;if(i>=open.length){isRunning=false;finishLiveRun('Visual assembly complete.','All available tiles were placed.');return}selectedTile=open[i];placeTile(open[i]);updateLiveRun('Local visual agent is assembling the board.',`Placing tile ${i+1} of ${open.length}.`,`Tile ${i+1} → cell ${open[i]+1}`);i++;timer=setTimeout(tick,180)};tick();return;
  }
  beginLiveRun('Local planner is mapping the board.','Searching only legal moves and puzzle constraints.');
  let plan=type==='sokoban'?solveSoko(structuredClone(state)):type==='maze'?solveMaze(structuredClone(state)):solveKlotski(structuredClone(state));
  if(!plan){finishLiveRun('No safe route was found.','The board was left unchanged.');toast('No valid plan found from this board.');log('RESULT','Local search found no safe route.','report');return}
  isRunning=true;$('#run-status').textContent='RUNNING';log('PLAN UPDATE',`Local planner verified a ${plan.length}-move route.`,'report',{observation:`The ${type} board is loaded and all ordinary puzzle rules are active.`,plan:'Use the deterministic local planner to follow a legal route.',reason:'Local demo mode is meant to validate the board and rendering loop, rather than evaluate a model.',expected:`The visible board should reach its solved state after ${plan.length} validated moves.`});updateLiveRun('Route verified.','The board will now animate one validated move at a time.',`${plan.length} safe moves queued`);
  let i=0;const tick=()=>{if(!isRunning)return;if(i>=plan.length){isRunning=false;finishLiveRun('Route finished.','All verified moves have been applied.');return}if(i%5===0){const batch=plan.slice(i,i+5).map(action=>type==='klotski'?`${action.id}${action.direction[0].toUpperCase()}`:({up:'↑ Up',down:'↓ Down',left:'← Left',right:'→ Right'})[action]);log('ACTION PLAN',`Local planner is starting actions ${i+1}–${Math.min(i+5,plan.length)}.`,'report',{reason:'This is the next verified segment of the local route.',actions:batch,expected:'Each move will render only after its puzzle-rule validation succeeds.'})}let action=plan[i],message;if(type==='klotski'){moveK(action.direction,true,action.id);message=`Slide ${String(i+1).padStart(2,'0')}/${String(plan.length).padStart(2,'0')} · ${action.id}${action.direction[0].toUpperCase()}`}else{move(action,true);message=friendlyAction(action,i,plan.length)}log('EXECUTING',message,'action');updateLiveRun('Executing verified route.',message,message);i++;if(!state.solved)timer=setTimeout(tick,240)};timer=setTimeout(tick,360)
}
function spawn(silent=false){let n=workspaces.length,w={id:`explorer-${Date.now()}-${n}`,name:`Explorer ${n}`,status:'ready',parent:'Private snapshot'};workspaces.push(w);$('#agent-count').textContent=workspaces.length;if(!silent){toast(`${w.name} has a private board snapshot.`);log('SPAWN',`${w.name} is exploring independently.`,'report')}return w}
function stop(silent=false){clearTimeout(timer);if(isRunning&&!silent){log('RUN CONTROL','Run paused before the next move.');$('#run-status').textContent='STOPPED';finishLiveRun('Run paused.','The board remains exactly where it was.')}isRunning=false}
function complete(){state.solved=true;stop(true);$('#run-status').textContent='SOLVED';log('RESULT',`Solved ${level().name} in the main workspace.`,'report');finishLiveRun('Puzzle solved.','Every goal is occupied; the final board is preserved.');toast('Puzzle solved ✦')}
function renderCards(){$('#puzzle-cards').innerHTML=Object.entries(puzzles).map(([id,p])=>`<button class="puzzle-card ${id===type?'active':''}" data-card="${id}"><p class="kicker">${p.levels.length} CHALLENGES</p><h3>${p.label}</h3><p>${p.description}</p><b>↗</b></button>`).join('');$$('[data-card]').forEach(b=>b.onclick=()=>{type=b.dataset.card;levelId=puzzles[type].levels[0].id;init()})}
function openDrawer(kind){let t=$(`#${kind}-template`);$('#drawer-content').innerHTML='';$('#drawer-content').append(t.content.cloneNode(true));$('#drawer-kicker').textContent=kind==='api'?'LOCAL CONFIGURATION':kind==='trace'?'RUN HISTORY':kind==='puzzles'?'PUZZLE LIBRARY':kind==='workspace'?'AGENT WORKSPACES':'AGENT CONTROL';$('#drawer').classList.add('show');$('#scrim').classList.add('show');renderDrawerContent(kind)}
function renderDrawerContent(kind){
  kind=kind||($('#drawer-kicker').textContent.includes('WORKSPACE')?'workspace':$('#drawer-kicker').textContent.includes('CONFIG')?'api':$('#drawer-kicker').textContent.includes('HISTORY')?'trace':$('#drawer-kicker').textContent.includes('LIBRARY')?'puzzles':'agents');
  if(kind==='agents'){
    $('#model-select').value=modelChoice;
    $('#model-id').value=modelId;
    const preset=$('#model-preset'),presetLabel=$('#model-preset-label'),customLabel=$('#custom-model-label'),help=$('#model-help'),mode=$('#run-mode'),modeHelp=$('#run-mode-help');
    const options=modelPresets[modelChoice]||[];
    presetLabel.hidden=!options.length;customLabel.hidden=!options.length;
    if(options.length){preset.innerHTML=`<option value="">Custom model ID…</option>${options.map(([id,label])=>`<option value="${id}" ${id===modelId?'selected':''}>${label}</option>`).join('')}`;preset.value=options.some(([id])=>id===modelId)?modelId:''}
    help.textContent=modelChoice==='claude'?'Preset IDs are current Anthropic API model IDs. Sonnet 5 is claude-sonnet-5 — it does not use a dated suffix.':modelChoice==='openai'?'Choose a current OpenAI preset for a local key/model check, or enter a model ID your account can access.': 'Runs entirely in the browser with deterministic puzzle solvers.';
    mode.value=runMode;
    mode.disabled=modelChoice!=='claude'||type==='jigsaw';
    modeHelp.textContent=type==='jigsaw'?'Run styles apply to live logic puzzles. Jigsaw has no route solver in this build.':modelChoice!=='claude'?'Run styles apply when a live Anthropic logic agent is selected.':runModeDetails[runMode];
    $('#model-select').onchange=e=>{const previous=modelChoice;modelChoice=e.target.value;if(modelId===modelDefaults[previous]||!modelId)modelId=modelDefaults[modelChoice];renderDrawerContent('agents')};
    preset.onchange=e=>{if(e.target.value){modelId=e.target.value;$('#model-id').value=modelId}else $('#model-id').focus()};
    $('#model-id').onchange=e=>{modelId=e.target.value.trim()||modelDefaults[modelChoice];if(options.some(([id])=>id===modelId))preset.value=modelId;else if(options.length)preset.value=''};
    mode.onchange=e=>{runMode=e.target.value;modeHelp.textContent=runModeDetails[runMode]};
    $('#run-from-drawer').onclick=run;
    $('#toggle-reference').hidden=type!=='jigsaw';
    $('#toggle-reference').onclick=()=>{if(type!=='jigsaw'){toast('Reference mode is available in Jigsaw.');return}state.reference=!state.reference;renderBoard();log('VISION MODE',state.reference?'Reference image provided to the agent.':'Reference image withheld from the agent.');};
    const explorers=workspaces.filter(w=>w.id!=='main');
    $('#agent-list').innerHTML=explorers.length?workspaces.map(w=>`<div class="agent-item"><div><b>${escapeHtml(w.name)}</b><small>${escapeHtml(w.parent)}</small></div><small>${escapeHtml(w.status)}</small></div>`).join(''):`<div class="trace-item empty-run"><b>Main agent is ready.</b><small>It will create a private explorer only when that helps the current puzzle.</small></div>`;
    const recentTrace=trace.filter(t=>t.kind!=='action').slice(-5);$('#trace-list').innerHTML=recentTrace.length?recentTrace.map((t,index)=>traceCard(t,Math.max(1,trace.length-recentTrace.length+index+1),true)).join(''):`<div class="trace-item empty-run"><b>No run yet.</b><small>Choose a provider and model, then the main agent will begin from this board.</small></div>`;
  }
  if(kind==='workspace'){
    $('#workspace-list').innerHTML=workspaces.map(w=>`<button class="workspace-item ${w.id===activeWorkspace?'active':''}" data-w="${w.id}"><span><b>${w.name}</b><small>${w.parent}</small></span><span>${w.status}</span></button>`).join('');
    $$('[data-w]').forEach(b=>b.onclick=()=>{activeWorkspace=b.dataset.w;$('#active-workspace').textContent=workspaces.find(w=>w.id===activeWorkspace).name;renderDrawerContent('workspace')});
  }
  if(kind==='trace'){const publicEntries=trace.filter(t=>t.kind!=='action');$('#full-trace').innerHTML=publicEntries.length?publicEntries.map((t,index)=>traceCard(t,index+1)).join(''):`<div class="trace-item empty-run"><b>No run yet.</b><small>The public operational journal will appear once an agent starts working.</small></div>`;}
  if(kind==='puzzles'){
    pickerType=pickerType in puzzles?pickerType:type;
    const renderPicker=()=>{const family=puzzles[pickerType],selected=family.levels.find(l=>l.id===$('#drawer-level-select').value)||family.levels[0];$('#puzzle-family-tabs').innerHTML=Object.entries(puzzles).map(([id,p])=>`<button class="puzzle-family-tab ${id===pickerType?'active':''}" data-family="${id}">${p.label} <small>${p.levels.length}</small></button>`).join('');$('#drawer-level-select').innerHTML=family.levels.map((l,index)=>`<option value="${l.id}" ${l.id===(pickerType===type?levelId:family.levels[0].id)?'selected':''}>${String(index+1).padStart(2,'0')} · ${l.name}</option>`).join('');const updateCard=()=>{const l=family.levels.find(x=>x.id===$('#drawer-level-select').value);$('#selected-level-card').innerHTML=`<b>${family.label} · ${l.name}</b><small>${l.kicker} · ${family.description}</small>`};updateCard();$$('[data-family]').forEach(b=>b.onclick=()=>{pickerType=b.dataset.family;renderPicker()});$('#drawer-level-select').onchange=updateCard;$('#load-selected-level').onclick=()=>{type=pickerType;levelId=$('#drawer-level-select').value;closeDrawer();init()}};
    renderPicker();
  }
  if(kind==='api'){
    fetch('/api/config').then(r=>r.json()).then(c=>{if(c.openai)$('#openai-key-status').classList.add('configured');if(c.anthropic)$('#anthropic-key-status').classList.add('configured')}).catch(()=>{});
    const verify=(provider)=>async()=>{const output=$(`#${provider}-test-result`);output.className='';output.textContent='Checking locally…';try{const response=await fetch('/api/test-provider',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider})});const result=await response.json();output.classList.add(result.ok?'good':'bad');output.textContent=result.ok?`Verified with ${result.model||provider}.`:result.error||'Provider check failed.'}catch{output.classList.add('bad');output.textContent='Could not reach the local server.'}};
    $('#test-openai').onclick=verify('openai');$('#test-anthropic').onclick=verify('anthropic');
  }
}
function closeDrawer(){$('#drawer').classList.remove('show');$('#scrim').classList.remove('show')}
$('#agents-tab').onclick=()=>openDrawer('agents');$('#workspace-tab').onclick=()=>openDrawer('workspace');$('#api-tab').onclick=()=>openDrawer('api');$('#trace-button').onclick=()=>openDrawer('trace');$$('[data-open-palette]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.openPalette));$$('[data-close]').forEach(b=>b.onclick=closeDrawer);$('#run-button').onclick=run;$('#reset-button').onclick=init;document.addEventListener('keydown',e=>{if(!dirs[e.key.replace('Arrow','').toLowerCase()])return;e.preventDefault();let d=e.key.replace('Arrow','').toLowerCase();if(type==='klotski')moveK(d);else move(d)});init();
$('#level-button').onclick=()=>openDrawer('puzzles');

const localRun = run;
async function playLiveActions(actions,source='Agent',generation=runGeneration,finalBatch=true){
  isRunning=true; $('#run-status').textContent='RUNNING';
  for(let index=0;index<actions.length;index++){
    if(!isRunning||generation!==runGeneration)break;
    const action=actions[index];let message;
    if(type==='sokoban'||type==='maze'){move(action,true);message=friendlyAction(action,index,actions.length)}
    else if(type==='jigsaw'){selectedTile=action.tile;placeTile(action.slot);message=`Tile ${action.tile+1} → board cell ${action.slot+1}`}
    log('EXECUTING',message,'action');
    updateLiveRun(`${source} is applying the verified route.`,message,message);
    await new Promise(resolve=>setTimeout(resolve,280));
  }
  isRunning=false;
  if(generation===runGeneration&&!state.solved&&finalBatch){$('#run-status').textContent='ERROR';failLiveRun(`${source} stopped before the board was solved.`,`${actions.length} validated steps were applied; no success was claimed.`)}
}
function failLiveRun(title,detail){if(!liveRun.startedAt)return;updateLiveRun(title,detail,'Run needs attention');clearInterval(liveRun.timer);liveRun.timer=null}
function publicTrace(entry){
  if(!entry||entry.label==='ACTION')return;
  const label=entry.label==='AGENT NOTE'?'AGENT NOTE':entry.label,kind=['BRANCH START','BRANCH REPORT','HELPER FILE','HELPER RUN','WORKSPACE'].includes(label)?'report':'';
  const meta={phase:entry.phase,explorer:entry.explorer,observation:entry.observation,plan:entry.plan,reason:entry.reason,expected:entry.expected,objective:entry.objective,report:entry.report,actions:entry.actions,file:entry.file,status:entry.status,output:entry.output,failure:entry.failure};
  log(label,entry.text,kind,meta);
  const activity=entry.plan||entry.reason||entry.report||entry.text;updateLiveRun('Claude is working in short batches.',briefTrace(activity,112),traceTitle(entry));
}
async function streamLogicRun(kind,generation){
  const body={model:modelId,solverMode:runMode,task:`Solve this ${kind} puzzle as the lead of a small visible team. First observe the board, then publish a concise human-facing checkpoint: Observation, Plan, Reason, and Expected result. On a nontrivial board, dispatch explorers with genuinely different jobs—such as deadlock analysis, target ordering, or player routing—and compare their findings before irreversible pushes. Write and run a small restricted Python helper when a graph or enumeration would genuinely clarify the next decision. Work in deliberate batches of at most five legal actions; every batch needs a specific public Reason tied to visible board facts. Keep the trace useful to a human, never expose hidden chain-of-thought.`};
  if(kind==='Klotski')body.level=level();else body.map=level().map;
  const response=await fetch(`/api/agent/${kind.toLowerCase()}/stream`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  if(!response.ok||!response.body){let message='The local server could not start a streamed agent run.';try{message=(await response.json()).error||message}catch{}throw new Error(message)}
  const decoder=new TextDecoder(),reader=response.body.getReader();let buffer='',pending=Promise.resolve(),result;
  const enqueueAction=event=>{pending=pending.then(async()=>{if(generation!==runGeneration||state.solved)return;const action=event.action??event.direction;let message,moved;if(kind==='Klotski'){message=`Committed slide ${String(event.index).padStart(2,'0')} · ${action.id}${action.direction[0].toUpperCase()}`;moved=moveK(action.direction,true,action.id)}else{message=`Committed move ${String(event.index).padStart(2,'0')} · ${({up:'↑ Up',down:'↓ Down',left:'← Left',right:'→ Right'})[action]}`;moved=move(action,true)}log('EXECUTION',message,'action');$('#run-status').textContent='RUNNING';if(!moved)throw new Error(`The streamed route proposed an illegal action: ${typeof action==='string'?action:`${action.id}${action.direction}`}.`);updateLiveRun(`${kind} agent is applying the next action batch.`,message,`Step ${event.index}`);await new Promise(resolve=>setTimeout(resolve,300))})};
  const handle=event=>{
    if(event.type==='started'){const style=event.runStyle||runModeLabels[runMode];log('RUN START',`Connected to ${event.model}. ${style}: the main agent will stream short ${kind} batches.`,'report');updateLiveRun(`${kind} agent is surveying the board.`,`${style}; the first deliberate batch is being prepared.`,'Model connected')}
    if(event.type==='trace')publicTrace(event.entry);
    if(event.type==='usage')setUsage(event.usage);
    if(event.type==='explorer'){const existing=workspaces.find(w=>w.name===event.explorer.name);if(!existing){const w=spawn(true);w.name=event.explorer.name;w.status='reported';w.parent='Frozen board snapshot';if($('#drawer').classList.contains('show')&&$('#drawer-kicker').textContent==='AGENT CONTROL')renderDrawerContent('agents')}}
    if(event.type==='action')enqueueAction(event);
    if(event.type==='complete')result=event.result;
  };
  while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line.trim())continue;try{handle(JSON.parse(line))}catch{throw new Error('The streamed agent response was malformed.')}}}
  if(buffer.trim())handle(JSON.parse(buffer));
  await pending;if(generation!==runGeneration)return;if(result?.usage)setUsage(result.usage);if(!result?.ok||!result?.solved)throw new Error(result?.error||'The agent stopped before it produced a solved board.');if(!state.solved)throw new Error('The streamed run ended before the visible board reached a solved state.');isRunning=false;$('#run-status').textContent='SOLVED';
  log('RUN COMPLETE',`${modelId} solved ${level().name} with ${result.actions.length} validated actions.${result.explorers?.length?` ${result.explorers.length} explorer report${result.explorers.length===1?' was':'s were'} used.`:' The main agent chose to work alone.'}`,'report');
}
run = async function(){
  const generation=runGeneration;
  let nudge;
  if($('#model-id'))modelId=$('#model-id').value.trim()||modelDefaults[modelChoice];
  if(modelChoice==='local')return localRun();
  if(modelChoice==='openai'){
    beginLiveRun('Checking the local OpenAI configuration.','The browser never sees the key; this asks only the local server.');
    try{const response=await fetch('/api/test-provider',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'openai',model:modelId})});const result=await response.json();if(!result.ok)throw new Error(result.error||'OpenAI rejected the configured key.');finishLiveRun('OpenAI key accepted.',`${result.model||modelId} is configured. The OpenAI puzzle-execution adapter is not implemented yet.`);toast('OpenAI key accepted; this build only runs Claude live agents.')}catch(error){failLiveRun('OpenAI configuration needs attention.','The key was rejected before any puzzle request was made.');toast(error.message)}return;
  }
  if(modelChoice!=='claude'){toast('Choose Local Solver, Claude, or configure an adapter.');return;}
  try{
    isRunning=true; $('#run-status').textContent='THINKING';beginLiveRun(type==='jigsaw'?'Claude is reviewing the visual reference.':'Claude main agent is surveying the board.',type==='jigsaw'?'Cataloguing visible regions before any virtual placement.':'Opening a private workspace and checking the puzzle state.');
    nudge=setTimeout(()=>updateLiveRun(type==='jigsaw'?'Claude is matching visual regions.':'Claude is preparing its first short action batch.',type==='jigsaw'?'Comparing the reference with the controlled tile map.':'It may inspect, delegate, or write a private helper before moving.',type==='jigsaw'?'Visual region check':'First batch pending'),1400);
    if(type==='sokoban'||type==='maze'||type==='klotski'){
      await streamLogicRun(type==='sokoban'?'sokoban':type==='maze'?'maze':'Klotski',generation); clearTimeout(nudge); return;
    }
    if(type==='jigsaw'){
      const response=await fetch('/api/agent/jigsaw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pieces:state.n*state.n,reference:state.reference,model:modelId})});
      clearTimeout(nudge);
      const result=await response.json(); if(generation!==runGeneration)return;if(!result.ok)throw new Error(result.error||'Visual agent run failed');
      setUsage(result.usage);
      (result.traces||[]).forEach(entry=>log(entry.label,entry.text,'report'));
      if(!result.actions.length){isRunning=false;$('#run-status').textContent='READY';finishLiveRun('Visual exploration paused.','No tile was placed because no visual board observation was supplied.');toast('No placement was guessed without a reference.');return;}
      updateLiveRun('Claude mapped the jigsaw reference.','Preparing the first explained virtual placement batch.',`${result.batches?.length||1} visual batches queued`);
      for(const [batchIndex,batch] of (result.batches||[{actions:result.actions,reason:'Reason: place the verified visual matches.'}]).entries()){
        if(generation!==runGeneration||state.solved)break;
        log('VISUAL DECISION',batch.reason,'report');
        updateLiveRun('Claude is applying a visual batch.',briefTrace(batch.reason,110),`Visual batch ${batchIndex+1}`);
        await playLiveActions(batch.actions,'Claude',generation,batchIndex===(result.batches?.length||1)-1);
      }
      return;
    }
  }catch(error){if(generation!==runGeneration)return;clearTimeout(nudge);isRunning=false;$('#run-status').textContent='ERROR';failLiveRun('The live run needs attention.',error.message);toast(error.message);log('RUN ERROR',error.message,'report');}
};
$('#run-button').onclick=run;
$('#undo-piece-button').onclick=undoJigsaw;
