const $ = (s) => document.querySelector(s);
const now = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
const sokobanLevels = [
  {id:'starter',name:'Starter · 1 crate',title:'Crate Course',kicker:'SOKOBAN · WARM-UP',map:['#####','# . #','# $ #','# @ #','#####']},
  {id:'fork',name:'Fork · 2 crates',title:'Two Crates, One Plan',kicker:'SOKOBAN · EASY ROUTE',map:['########','# .  . #','# $  $ #','#  @   #','########']},
  {id:'turn',name:'Turn · 2 crates',title:'Corner Discipline',kicker:'SOKOBAN · THINK AHEAD',map:['########','# .    #','# $ ## #','#   $  #','#  @ . #','########']}
];
const klotskiLevels = [
  {id:'studio',name:'Studio · exit the blue block',title:'Long-axis Studio',kicker:'KLOTSKI · LONG-AXIS SLIDERS',pieces:[{id:'target',x:0,y:2,w:2,h:1,target:true},{id:'top',x:1,y:0,w:2,h:1},{id:'v1',x:3,y:1,w:1,h:2},{id:'v2',x:1,y:3,w:1,h:2},{id:'bottom',x:3,y:4,w:2,h:1}]},
  {id:'gallery',name:'Gallery · more blocks',title:'Sliding Gallery',kicker:'KLOTSKI · CAREFUL EXIT',pieces:[{id:'target',x:0,y:2,w:2,h:1,target:true},{id:'top',x:1,y:0,w:2,h:1},{id:'v1',x:3,y:0,w:1,h:3},{id:'v2',x:4,y:0,w:1,h:3},{id:'v3',x:2,y:2,w:1,h:2},{id:'mid',x:3,y:3,w:2,h:1},{id:'bottom',x:0,y:4,w:2,h:1}]}
];
const workspaces=[{id:'main',name:'Main Agent',role:'Puzzle operator',parent:'Authoritative workspace',status:'ready',icon:'M',reports:[]}];
let selectedWorkspace='main',puzzleType='sokoban',levelId='fork',state,timeline=[],trace=[],runningTimer=null,isRunning=false,selectedPiece=null;
const currentWorkspace=()=>workspaces.find(w=>w.id===selectedWorkspace);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2600)}
function addTimeline(message,icon='→'){timeline.unshift({time:now(),message,icon});renderTimeline()}
function addTrace(label,message,kind=''){trace.unshift({label,message,kind});renderTrace()}
function setStatus(status){const ws=currentWorkspace();ws.status=status;const label=$('#run-status');label.textContent=status==='running'?'RUNNING':status==='done'?'SOLVED':status==='stopped'?'STOPPED':'READY';label.className=`status-${status==='done'?'solved':status}`;const badge=$('#agent-state-badge');badge.textContent=status==='running'?'Working':status==='done'?'Solved':status==='stopped'?'Stopped':'Ready';badge.className=`state-badge ${status==='done'?'done':status}`;renderWorkspaces()}
function renderWorkspaces(){$('#workspace-list').innerHTML=workspaces.map(w=>`<button class="workspace ${w.id===selectedWorkspace?'active':''}" data-workspace="${w.id}" type="button"><span class="workspace-icon">${w.icon}</span><span class="workspace-text"><strong>${w.name}</strong><small>${w.parent==='Authoritative workspace'?'Authoritative run':w.role}</small></span><span class="workspace-status ${w.status}"></span></button>`).join('');document.querySelectorAll('[data-workspace]').forEach(el=>el.addEventListener('click',()=>switchWorkspace(el.dataset.workspace)))}
function switchWorkspace(id){if(isRunning){toast('Let the current run finish or stop it before switching.');return}selectedWorkspace=id;const ws=currentWorkspace();$('#workspace-title').textContent=ws.name;$('#control-agent-name').textContent=ws.name;$('#agent-role').textContent=ws.role;$('#agent-parent').textContent=ws.parent;$('#agent-avatar').textContent=ws.icon;renderWorkspaces();renderReports();addTrace('WORKSPACE',`Opened ${ws.name}'s isolated puzzle workspace.`)}
function renderTimeline(){$('#timeline').innerHTML=timeline.length?timeline.map(e=>`<li><span class="event-icon">${e.icon}</span><time>${e.time}</time><span>${e.message}</span></li>`).join(''):'<li><span class="event-icon">·</span><span>Actions, observations, and delegation events will appear here.</span></li>'}
function renderTrace(){$('#trace').innerHTML=trace.length?trace.map(e=>`<div class="trace-entry ${e.kind}"><strong>${e.label}</strong>${e.message}</div>`).join(''):'<div class="trace-entry"><strong>READY</strong>Waiting for a puzzle run.</div>'}
function renderReports(){const reports=currentWorkspace().reports||[];$('#child-reports').innerHTML=reports.length?reports.map(r=>`<article class="child-report"><header><strong>${r.name}</strong><span class="${r.good?'report-good':'report-warn'}">${r.status}</span></header><p>${r.message}</p></article>`).join(''):'<div class="child-report"><p>No child reports yet. Choose “Delegate alternatives” to see an agent team explore safely.</p></div>'}
function level(){return(puzzleType==='sokoban'?sokobanLevels:klotskiLevels).find(l=>l.id===levelId)}
function parseSokoban(map){const goals=[],crates=[];let player;const base=map.map((row,y)=>[...row].map((c,x)=>{if('.+*'.includes(c))goals.push([x,y]);if('$*'.includes(c))crates.push([x,y]);if('@+'.includes(c))player=[x,y];return c==='#'?'#':' '}));return{base,goals,crates,player,steps:0,pushes:0,solved:false}}
function initializePuzzle(){stopAgent(true);const l=level();timeline=[];trace=[];selectedPiece=null;state=puzzleType==='sokoban'?parseSokoban(l.map):{pieces:structuredClone(l.pieces),steps:0,solved:false};$('#puzzle-title').textContent=l.title;$('#puzzle-kicker').textContent=l.kicker;$('#step-count').textContent='0';$('#push-count').textContent='0';$('#cost-value').textContent='$0.00';$('#harness-label').textContent='STRUCTURED LOGIC HARNESS';$('#puzzle-help').textContent=puzzleType==='sokoban'?'Use arrow keys or the controls to move. Push every crate onto a glowing goal.':'Select a block, then use arrow keys. Blocks move only along their longer side; guide the blue block to the exit.';addTrace('OBSERVATION',puzzleType==='sokoban'?'Board loaded. Goals, crates, player position, and legal directions are available.':'Board loaded. Long-axis rule is active: horizontal pieces only slide left/right, vertical pieces only slide up/down.');addTimeline(`${l.title} loaded.`,'◌');setStatus('ready');renderBoard();renderTimeline();renderTrace();renderReports();$('#game-stage').focus()}
function renderBoard(){puzzleType==='sokoban'?renderSokoban():renderKlotski()}
function renderSokoban(){const rows=state.base.length,cols=state.base[0].length,goals=new Set(state.goals.map(p=>p.join(','))),crates=new Set(state.crates.map(p=>p.join(','))),player=state.player.join(',');$('#game-stage').className='game-stage sokoban-stage';$('#game-stage').innerHTML=`<div class="sokoban-board" style="--cols:${cols};--rows:${rows}">${state.base.map((row,y)=>row.map((cell,x)=>{const k=`${x},${y}`,g=goals.has(k),c=crates.has(k);return`<div class="soko-cell ${cell==='#'?'wall':'floor'} ${g?'goal':''}">${c?`<span class="crate ${g?'on-goal':''}"></span>`:''}${k===player?'<span class="player"></span>':''}</div>`}).join('')).join('')}</div>`;$('#manual-controls').innerHTML='<div class="control-pad"><button data-move="up" aria-label="Move up">↑</button><button data-move="left" aria-label="Move left">←</button><button data-move="down" aria-label="Move down">↓</button><button data-move="right" aria-label="Move right">→</button></div>';document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>attemptSokoMove(b.dataset.move,false)))}
const key=(x,y)=>`${x},${y}`;function isWall(x,y){return y<0||y>=state.base.length||x<0||x>=state.base[0].length||state.base[y][x]==='#'}function crateAt(x,y){return state.crates.findIndex(c=>c[0]===x&&c[1]===y)}
function attemptSokoMove(dir,agent){if(state.solved||(isRunning&&!agent))return false;const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir],[px,py]=state.player,nx=px+d[0],ny=py+d[1];if(isWall(nx,ny)){if(!agent)addTrace('ACTION REJECTED','A wall blocks that route.');return false}const ci=crateAt(nx,ny);let push=false;if(ci>=0){const bx=nx+d[0],by=ny+d[1];if(isWall(bx,by)||crateAt(bx,by)>=0){if(!agent)addTrace('ACTION REJECTED','That crate cannot be pushed there.');return false}state.crates[ci]=[bx,by];state.pushes++;push=true}state.player=[nx,ny];state.steps++;$('#step-count').textContent=state.steps;$('#push-count').textContent=state.pushes;renderSokoban();if(!agent){addTimeline(`${push?'Pushed a crate':'Moved'} ${dir}.`,push?'⇢':'→');addTrace('MANUAL ACTION',`${push?'Pushed a crate':'Moved'} ${dir}.`,'action')}if(state.goals.every(g=>crateAt(g[0],g[1])>=0))completePuzzle();return true}
function renderKlotski(){$('#game-stage').className='game-stage klotski-stage';$('#game-stage').innerHTML=`<div class="klotski-instruction">Each block is constrained to its long axis. The violet target must slide right through the illuminated exit.</div><div class="klotski-board"><div class="k-grid"></div><div class="k-exit">»</div>${state.pieces.map(p=>`<button class="k-piece ${p.target?'target':''} ${p.id===selectedPiece?'selected':''}" data-piece="${p.id}" style="--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}" aria-label="${p.id} ${p.w>p.h?'horizontal':'vertical'} block"></button>`).join('')}</div>`;$('#manual-controls').innerHTML='<div class="control-pad"><button data-kmove="up" aria-label="Move selected up">↑</button><button data-kmove="left" aria-label="Move selected left">←</button><button data-kmove="down" aria-label="Move selected down">↓</button><button data-kmove="right" aria-label="Move selected right">→</button></div>';document.querySelectorAll('[data-piece]').forEach(p=>p.addEventListener('click',()=>{selectedPiece=p.dataset.piece;renderKlotski();addTrace('SELECTION',`Selected ${selectedPiece}. Its long-axis constraint is active.`)}));document.querySelectorAll('[data-kmove]').forEach(b=>b.addEventListener('click',()=>attemptKlotskiMove(b.dataset.kmove,false)))}
function occupiedExcept(piece){const occ=new Set();state.pieces.filter(p=>p.id!==piece.id).forEach(p=>{for(let y=p.y;y<p.y+p.h;y++)for(let x=p.x;x<p.x+p.w;x++)occ.add(key(x,y))});return occ}
function attemptKlotskiMove(dir,agent){if(state.solved||(isRunning&&!agent))return false;const piece=state.pieces.find(p=>p.id===selectedPiece)||state.pieces.find(p=>p.target);if(!piece){toast('Select a block first.');return false}const horizontal=piece.w>piece.h;if((horizontal&&(dir==='up'||dir==='down'))||(!horizontal&&(dir==='left'||dir==='right'))){if(!agent)addTrace('ACTION REJECTED',`${piece.id} can only move along its ${horizontal?'horizontal':'vertical'} long axis.`);return false}const delta={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir],nx=piece.x+delta[0],ny=piece.y+delta[1];if(piece.target&&dir==='right'&&piece.y===2&&piece.x===3){state.solved=true;state.steps++;$('#step-count').textContent=state.steps;renderKlotski();completePuzzle();return true}const occ=occupiedExcept(piece);for(let y=ny;y<ny+piece.h;y++)for(let x=nx;x<nx+piece.w;x++)if(x<0||x>=5||y<0||y>=5||occ.has(key(x,y))){if(!agent)addTrace('ACTION REJECTED','That slide is blocked.');return false}piece.x=nx;piece.y=ny;state.steps++;$('#step-count').textContent=state.steps;renderKlotski();if(!agent){addTimeline(`Slid ${piece.id} ${dir}.`,'⇢');addTrace('MANUAL ACTION',`Slid ${piece.id} ${dir}.`,'action')}return true}
function completePuzzle(){state.solved=true;stopAgent(true);setStatus('done');addTimeline('Puzzle solved. The authoritative board is complete.','✦');addTrace('RESULT','Success. The main workspace reached its puzzle goal.','report');$('#success-copy').textContent=`Solved in ${state.steps} moves${puzzleType==='sokoban'?` with ${state.pushes} crate pushes`:''}.`;$('#success-overlay').classList.add('show');$('#success-overlay').setAttribute('aria-hidden','false')}
function encodeSoko(s){return`${s.player.join(',')}|${s.crates.map(c=>c.join(',')).sort().join(';')}`}function solveSokoban(initial){const queue=[structuredClone(initial)],seen=new Set([encodeSoko(initial)]),dirs=[['up',0,-1],['down',0,1],['left',-1,0],['right',1,0]];let count=0;const wall=(s,x,y)=>y<0||y>=s.base.length||x<0||x>=s.base[0].length||s.base[y][x]==='#',at=(s,x,y)=>s.crates.findIndex(c=>c[0]===x&&c[1]===y);while(queue.length&&count++<30000){const s=queue.shift();if(s.goals.every(g=>at(s,g[0],g[1])>=0))return s.path||[];for(const[name,dx,dy]of dirs){const n=structuredClone(s);n.path=[...(s.path||[]),name];const[px,py]=n.player,nx=px+dx,ny=py+dy;if(wall(n,nx,ny))continue;const ci=at(n,nx,ny);if(ci>=0){const bx=nx+dx,by=ny+dy;if(wall(n,bx,by)||at(n,bx,by)>=0)continue;n.crates[ci]=[bx,by]}n.player=[nx,ny];const code=encodeSoko(n);if(!seen.has(code)){seen.add(code);queue.push(n)}}}return null}
function spawnExplorer(auto=false){const n=workspaces.filter(w=>w.id!=='main').length+1,ws={id:`child-${Date.now()}-${n}`,name:`Explorer ${n}`,role:'Independent strategy',parent:'Child of Main Agent',status:'ready',icon:String(n),reports:[]};workspaces.push(ws);renderWorkspaces();if(!auto){currentWorkspace().reports.push({name:ws.name,status:'READY',good:true,message:'Private snapshot created. This explorer can safely test a different route.'});renderReports();toast(`${ws.name} spawned with an isolated snapshot.`)}return ws}
function simulateDelegation(solution){const main=workspaces.find(w=>w.id==='main'),a=spawnExplorer(true),b=spawnExplorer(true);a.status='done';b.status='done';main.reports.unshift({name:a.name,status:'REPORTED',good:false,message:'Tested a premature crate push. It creates a blocked route, so the main run avoided it.'});main.reports.unshift({name:b.name,status:'REPORTED',good:true,message:`Found a valid ${solution.length}-move route from its private board snapshot.`});addTimeline('Spawned two isolated explorers to compare routes.','⌘');addTrace('DELEGATION','Explorer 1 rejected a risky push; Explorer 2 returned a verified route.','report');renderWorkspaces();renderReports()}
function runAgent(){if(isRunning||state.solved)return;const model=$('#model-select').value;if(model!=='local'){toast('This first build runs the local solver so it can be tested without an API key. API adapters are the next runtime layer.');return}if(puzzleType==='klotski'){toast('The visual/long-axis agent runner is queued for the next harness. Use the controls to test Klotski today.');addTrace('HARNESS NOTE','Klotski is interactive and fully validated; the deterministic agent runner currently targets Sokoban.');return}const solution=solveSokoban(structuredClone(state));if(!solution){toast('No route was found from this board state. Reset and try again.');addTrace('RESULT','The local search could not find a valid route from this state.','report');return}isRunning=true;setStatus('running');$('#run-button').disabled=true;$('#run-button').textContent='Running…';addTimeline('Agent received a structured board observation.','◉');addTrace('PLAN',`Searching the state space. A route with ${solution.length} actions is available.`,'action');if($('#strategy-select').value==='explore')simulateDelegation(solution);let i=0;const tick=()=>{if(!isRunning)return;if(i>=solution.length){isRunning=false;return}const move=solution[i++];attemptSokoMove(move,true);addTimeline(`Agent applied ${move}${i<solution.length?'':' and completed the route'}.`,'→');if(i%4===0)addTrace('PROGRESS',`Applied ${i} of ${solution.length} planned actions.`,'action');$('#cost-value').textContent=`$${(i*.00008).toFixed(4)}`;if(!state.solved)runningTimer=setTimeout(tick,210)};runningTimer=setTimeout(tick,520)}
function stopAgent(silent=false){if(runningTimer)clearTimeout(runningTimer);const was=isRunning;isRunning=false;$('#run-button').disabled=false;$('#run-button').innerHTML='<span class="play-icon">▶</span> Run agent';if(was){setStatus('stopped');if(!silent){addTimeline('Run stopped by user.','■');addTrace('RUN CONTROL','Paused the active action queue.')}}}
function populateLevels(){const levels=puzzleType==='sokoban'?sokobanLevels:klotskiLevels;if(!levels.some(l=>l.id===levelId))levelId=levels[0].id;$('#level-select').innerHTML=levels.map(l=>`<option value="${l.id}" ${l.id===levelId?'selected':''}>${l.name}</option>`).join('');document.querySelectorAll('[data-puzzle]').forEach(b=>b.classList.toggle('active',b.dataset.puzzle===puzzleType))}
function nextLevel(){$('#success-overlay').classList.remove('show');const levels=puzzleType==='sokoban'?sokobanLevels:klotskiLevels,idx=levels.findIndex(l=>l.id===levelId);levelId=levels[(idx+1)%levels.length].id;populateLevels();initializePuzzle()}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const dir=e.key.replace('Arrow','').toLowerCase();puzzleType==='sokoban'?attemptSokoMove(dir,false):attemptKlotskiMove(dir,false)}});document.querySelectorAll('[data-puzzle]').forEach(b=>b.addEventListener('click',()=>{puzzleType=b.dataset.puzzle;levelId=(puzzleType==='sokoban'?sokobanLevels:klotskiLevels)[0].id;populateLevels();initializePuzzle()}));$('#level-select').addEventListener('change',e=>{levelId=e.target.value;initializePuzzle()});$('#run-button').addEventListener('click',runAgent);$('#stop-button').addEventListener('click',()=>stopAgent());$('#reset-button').addEventListener('click',initializePuzzle);$('#spawn-agent-button').addEventListener('click',()=>spawnExplorer());$('#clear-timeline').addEventListener('click',()=>{timeline=[];renderTimeline()});$('#next-level-button').addEventListener('click',nextLevel);populateLevels();renderWorkspaces();initializePuzzle();
