import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { execFile as execFileCallback } from 'node:child_process';
import { extname, join, normalize } from 'node:path';
import { promisify } from 'node:util';

const root = process.cwd();
const execFile=promisify(execFileCallback);
const pythonRunner=join(root,'agent_python_sandbox.py');
const envPath = join(root, '.env.local');
const env = {};
if (existsSync(envPath)) {
  const lines = (await readFile(envPath, 'utf8')).split(/\r?\n/);
  for (const line of lines) { const match=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/); if (match) env[match[1]]=match[2].replace(/^['"]|['"]$/g,''); }
}

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.md':'text/markdown; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml'};
const keyFor = provider => provider === 'anthropic' ? (process.env.ANTHROPIC_API_KEY || env.ANTHROPIC_API_KEY) : (process.env.OPENAI_API_KEY || env.OPENAI_API_KEY);
const json = (res,status,payload) => { res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(payload)); };
const readJson = req => new Promise((resolve,reject)=>{let raw='';req.on('data',chunk=>raw+=chunk);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(error){reject(error)}});req.on('error',reject)});
const DEFAULT_CLAUDE_MODEL='claude-sonnet-5';
const safeModel=(model,fallback)=>typeof model==='string'&&/^[a-zA-Z0-9._:-]{2,120}$/.test(model)?model:fallback;
const normaliseSolverMode=mode=>['free','verify','assist'].includes(mode)?mode:'free';
const solverModeLabel=mode=>({free:'Free agent · no route hints',verify:'Action checker · self-proposed batches only',assist:'Solver aid · route on request'})[mode];
const thinkingConfigFor=model=>/claude-(sonnet-5|opus)/.test(model)?{thinking:{type:'disabled'}}:{};
const MAX_EXPLORERS=3;
const jigsawAssets={'/assets/cat.jpg':'cat.jpg','/assets/dog.jpg':'dog.jpg','/assets/mona-lisa.jpg':'mona-lisa.jpg','/assets/great-wave.jpg':'great-wave.jpg','/assets/starry-night.jpg':'starry-night.jpg'};
const jigsawAssetPath=asset=>join(root,'assets',jigsawAssets[asset]||'cat.jpg');
const directionMap={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
const cellKey=(x,y)=>`${x},${y}`;
const cleanPublicText=(value,limit=260)=>String(value||'').replace(/\s+/g,' ').trim().slice(0,limit);
const safeWorkspaceName=(value,fallback='notes.md')=>{const raw=String(value||fallback).replace(/[^a-zA-Z0-9._-]/g,'_').replace(/^\.+/,'').slice(0,80)||fallback;return/\.(md|py)$/.test(raw)?raw:`${raw}.md`;};

async function runWorkspacePython(folder,name){
  try{const result=await execFile('python3',['-I',pythonRunner,join(folder,name)],{cwd:folder,env:{PATH:process.env.PATH||'/usr/bin:/bin'},timeout:2200,maxBuffer:12000});return{ok:true,output:cleanPublicText(result.stdout,8000)||'(helper completed without stdout)'};}
  catch(error){const detail=cleanPublicText(error.stdout||error.stderr||error.message,8000)||'The helper could not run.';return{ok:false,error:detail};}
}

function providerError(body,status,model='') {
  const message=String(body?.error?.message||'');
  if(/api key|authentication|unauthorized/i.test(message)) return 'Provider rejected the configured key. Replace it in .env.local and restart the local server.';
  if(status===404&&model==='claude-sonnet-5-20251001') return 'claude-sonnet-5-20251001 is not an Anthropic model ID. Choose claude-sonnet-5 (no dated suffix), or choose a curated preset.';
  if(status===404) return `Model “${model||'selected model'}” was not found or is unavailable to this provider account. Choose a curated preset or enter an exact model ID your account can access.`;
  return `Provider request failed (HTTP ${status}). ${message||'Check the selected model and local server configuration.'}`;
}
function normaliseMap(map){const width=Math.max(...map.map(row=>row.length));return map.map(row=>row.padEnd(width,'#'));}
function parseSokoban(map){
  const goals=[],crates=[];let player;
  const base=normaliseMap(map).map((row,y)=>[...row].map((char,x)=>{if('.+*'.includes(char))goals.push([x,y]);if('$*'.includes(char))crates.push([x,y]);if('@+'.includes(char))player=[x,y];return char==='#'?'#':' '}));
  if(!player||!goals.length)throw new Error('This Sokoban map needs a player and at least one target.');
  return {base,goals,crates,player,actions:[]};
}
function serialiseSokoban(env){return env.base.map((row,y)=>row.map((base,x)=>{const key=cellKey(x,y);if(base==='#')return '#';const crate=env.crates.some(c=>cellKey(...c)===key),goal=env.goals.some(g=>cellKey(...g)===key),player=cellKey(...env.player)===key;return player?(goal?'+':'@'):crate?(goal?'*':'$'):(goal?'.':' ')}).join('')).join('\n');}
function isWall(env,x,y){return y<0||y>=env.base.length||x<0||x>=env.base[0].length||env.base[y][x]==='#';}
function crateIndex(env,x,y){return env.crates.findIndex(crate=>crate[0]===x&&crate[1]===y);}
function applySokoban(env,direction){const [dx,dy]=directionMap[direction]||[];if(dx===undefined)return{ok:false,error:'Unknown direction'};const[x,y]=env.player,nx=x+dx,ny=y+dy;if(isWall(env,nx,ny))return{ok:false,error:'Wall blocks that move'};const index=crateIndex(env,nx,ny);if(index>=0){const bx=nx+dx,by=ny+dy;if(isWall(env,bx,by)||crateIndex(env,bx,by)>=0)return{ok:false,error:'Crate cannot be pushed there'};env.crates[index]=[bx,by];}env.player=[nx,ny];env.actions.push(direction);return{ok:true,solved:env.goals.every(goal=>crateIndex(env,...goal)>=0),board:serialiseSokoban(env)};}
function solveSokoban(initial){const encode=state=>`${state.player.join(',')}|${state.crates.map(c=>c.join(',')).sort().join(';')}`,queue=[structuredClone(initial)],seen=new Set([encode(initial)]);let inspected=0;while(queue.length&&inspected++<180000){const state=queue.shift();if(state.goals.every(goal=>crateIndex(state,...goal)>=0))return state.actions||[];for(const direction of Object.keys(directionMap)){const next=structuredClone(state),result=applySokoban(next,direction);if(result.ok){const code=encode(next);if(!seen.has(code)){seen.add(code);queue.push(next)}}}}return null;}

function parseMaze(map){const raw=parseSokoban(map);if(raw.goals.length!==1)throw new Error('A maze must have exactly one exit.');return{base:raw.base,player:raw.player,goal:raw.goals[0],actions:[]};}
function serialiseMaze(env){return env.base.map((row,y)=>row.map((base,x)=>{if(base==='#')return '#';const key=cellKey(x,y);if(key===cellKey(...env.player))return '@';if(key===cellKey(...env.goal))return '.';return ' ';}).join('')).join('\n');}
function applyMaze(env,direction){const[dx,dy]=directionMap[direction]||[];if(dx===undefined)return{ok:false,error:'Unknown direction'};const[x,y]=env.player,nx=x+dx,ny=y+dy;if(isWall(env,nx,ny))return{ok:false,error:'Wall blocks that move'};env.player=[nx,ny];env.actions.push(direction);return{ok:true,solved:cellKey(...env.player)===cellKey(...env.goal),board:serialiseMaze(env)};}
function solveMaze(initial){const queue=[{position:initial.player,path:[]}],seen=new Set([cellKey(...initial.player)]);while(queue.length){const item=queue.shift();if(cellKey(...item.position)===cellKey(...initial.goal))return item.path;for(const[direction,[dx,dy]]of Object.entries(directionMap)){const next=[item.position[0]+dx,item.position[1]+dy],key=cellKey(...next);if(!isWall(initial,...next)&&!seen.has(key)){seen.add(key);queue.push({position:next,path:[...item.path,direction]})}}}return null;}

function parseKlotski(level){
  const cols=Number(level?.cols||6),rows=Number(level?.rows||6),exitRow=Number(level?.exitRow??2),pieces=structuredClone(level?.pieces||[]);
  if(!Number.isInteger(cols)||!Number.isInteger(rows)||!pieces.length)throw new Error('Invalid Klotski level.');
  const ids=new Set();for(const piece of pieces){if(!piece.id||ids.has(piece.id)||!Number.isInteger(piece.x)||!Number.isInteger(piece.y)||!Number.isInteger(piece.w)||!Number.isInteger(piece.h)||piece.w===piece.h)throw new Error('Klotski tiles must have unique IDs and a long axis.');ids.add(piece.id);}
  const env={cols,rows,exitRow,pieces,actions:[]};for(const piece of pieces)if(!canMoveKlotskiBounds(env,piece.x,piece.y,piece,piece))throw new Error('Klotski level contains an invalid or overlapping tile.');
  return env;
}
function occupiedKlotski(env,except){const occupied=new Set();for(const piece of env.pieces)if(piece!==except)for(let y=piece.y;y<piece.y+piece.h;y++)for(let x=piece.x;x<piece.x+piece.w;x++)occupied.add(cellKey(x,y));return occupied;}
function canMoveKlotskiBounds(env,x,y,piece,except){const occupied=occupiedKlotski(env,except);for(let yy=y;yy<y+piece.h;yy++)for(let xx=x;xx<x+piece.w;xx++)if(xx<0||xx>=env.cols||yy<0||yy>=env.rows||occupied.has(cellKey(xx,yy)))return false;return true;}
function canMoveKlotski(env,piece,direction){if(!piece||!directionMap[direction])return false;const horizontal=piece.w>piece.h;if((horizontal&&['up','down'].includes(direction))||(!horizontal&&['left','right'].includes(direction)))return false;const[dx,dy]=directionMap[direction];return canMoveKlotskiBounds(env,piece.x+dx,piece.y+dy,piece,piece);}
function serialiseKlotski(env){const board=Array.from({length:env.rows},()=>Array(env.cols).fill('.'));for(const piece of env.pieces)for(let y=piece.y;y<piece.y+piece.h;y++)for(let x=piece.x;x<piece.x+piece.w;x++)board[y][x]=piece.id;return `Exit: right side of row ${env.exitRow + 1}\n${board.map(row=>row.map(cell=>String(cell).padStart(2,' ')).join(' ')).join('\n')}`;}
function normaliseKlotskiAction(action){const raw=action||{},id=raw.id??raw.block??raw.block_id??raw.piece_id??raw.piece??raw.tile,direction=raw.direction;return{id:id===undefined?'':String(id),direction};}
function applyKlotski(env,action){const normalized=normaliseKlotskiAction(action),{id,direction}=normalized;if(!id)return{ok:false,error:'Every Klotski action needs a tile id, for example {"id":"2","direction":"down"}.'};const piece=env.pieces.find(item=>item.id===id);if(!piece)return{ok:false,error:`Tile ${id} does not exist. Use one of: ${env.pieces.map(item=>item.id).join(', ')}.`};if(!canMoveKlotski(env,piece,direction))return{ok:false,error:`${id}${String(direction||'')[0]?.toUpperCase()||''} is blocked or off-axis`};const[dx,dy]=directionMap[direction];piece.x+=dx;piece.y+=dy;env.actions.push(normalized);return{ok:true,action:normalized,solved:Boolean(piece.target&&piece.y===env.exitRow&&piece.x===env.cols-piece.w),board:serialiseKlotski(env)};}
function solveKlotski(initial){const encode=state=>state.pieces.map(piece=>`${piece.id}:${piece.x},${piece.y}`).join('|'),queue=[structuredClone(initial)],seen=new Set([encode(initial)]);let inspected=0;while(queue.length&&inspected++<150000){const state=queue.shift(),target=state.pieces.find(piece=>piece.target);if(target&&target.y===state.exitRow&&target.x===state.cols-target.w)return state.actions||[];for(const piece of state.pieces)for(const direction of Object.keys(directionMap)){if(!canMoveKlotski(state,piece,direction))continue;const next=structuredClone(state),moving=next.pieces.find(item=>item.id===piece.id),[dx,dy]=directionMap[direction];moving.x+=dx;moving.y+=dy;next.actions=[...(state.actions||[]),{id:piece.id,direction}];const code=encode(next);if(!seen.has(code)){seen.add(code);queue.push(next)}}}return null;}

const usageFrom=body=>({inputTokens:Number(body?.usage?.input_tokens||0),outputTokens:Number(body?.usage?.output_tokens||0)});
const addUsage=(total,usage)=>({inputTokens:total.inputTokens+usage.inputTokens,outputTokens:total.outputTokens+usage.outputTokens});
function estimateClaudeCost(model,usage){const id=String(model).toLowerCase();const rate=id.includes('haiku')?[1,5]:id.includes('sonnet')?[2,10]:id.includes('opus')?[5,25]:id.includes('fable')?[10,50]:null;return rate?(usage.inputTokens*rate[0]+usage.outputTokens*rate[1])/1_000_000:null;}
const usageSummary=(model,usage)=>({model,inputTokens:usage.inputTokens,outputTokens:usage.outputTokens,estimatedCostUsd:estimateClaudeCost(model,usage)});

function conciseExplorerReport(text){const raw=String(text||'').replace(/```[\s\S]*?```/g,'').replace(/\s+/g,' ').trim();try{const parsed=JSON.parse(raw),finding=cleanPublicText(parsed.finding,220),next=cleanPublicText(parsed.next,180),confidence=cleanPublicText(parsed.confidence,30);if(finding)return`${finding}${next?` Next: ${next}`:''}${confidence?` (${confidence} confidence)`:''}`.slice(0,440)}catch{}return cleanPublicText(raw,440)||'Explorer returned no usable public finding.';}
async function runAnthropicExplorer(key,board,task,model,kind){
  const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:140,system:`You are a focused ${kind} exploration subagent. Return ONLY valid JSON with exactly these short string fields: {"finding":"one board-grounded conclusion","next":"one concrete recommendation","confidence":"low, medium, or high"}. Do not include a board map, coordinate transcript, chain-of-thought, Markdown, or preamble. If uncertain, say so in finding.`,messages:[{role:'user',content:`Question: ${String(task||'Assess one distinct strategy.').slice(0,700)}\n\nBoard:\n${board}`}],...thinkingConfigFor(model)})});
  const body=await response.json(),report=conciseExplorerReport((body.content||[]).filter(item=>item.type==='text').map(item=>item.text||'').join(''));return response.ok?{ok:true,report,usage:usageFrom(body)}:{ok:false,report:`Explorer could not run: ${providerError(body,response.status,model)}`,usage:usageFrom(body)};
}
function publicAgentNote(text){const note=String(text||'').replace(/\s+/g,' ').trim();if(!note||/\b(let me|i need|i'll|i will|think|analy[sz]e|parse|coordinate|row\s*\d|col(?:umn)?\s*\d)\b/i.test(note))return'';return note.slice(0,220);}
function actionSchema(kind){const isKlotski=String(kind).toLowerCase()==='klotski';return isKlotski?{type:'array',items:{type:'object',properties:{id:{type:'string',description:'The printed tile number as a string, for example "2". This field is required.'},direction:{type:'string',enum:['up','down','left','right']}},required:['id','direction']},minItems:1,maxItems:5}:{type:'array',items:{type:'string',enum:['up','down','left','right']},minItems:1,maxItems:5};}
function prettyAction(kind,action){const isKlotski=String(kind).toLowerCase()==='klotski',normalized=isKlotski?normaliseKlotskiAction(action):action;return isKlotski?`${normalized.id}${normalized.direction[0].toUpperCase()}`:normalized;}
async function runAnthropicStructuredAgent({kind,env,serialise,apply,solve,isSolved,model,onEvent,task,solverMode}){
  const key=keyFor('anthropic');if(!key)return{ok:false,error:'ANTHROPIC_API_KEY is not configured.'};
  const selectedModel=safeModel(model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL),runId=`run-${Date.now()}`,traces=[],explorers=[],mode=normaliseSolverMode(solverMode),workspaceFolder=join('/private/tmp','agent-arcade-workspaces',runId),workspaceFiles=new Set();let usage={inputTokens:0,outputTokens:0},idleToolTurns=0,blankWorkspaceWrites=0;
  // Sonnet 5 enables adaptive thinking by default. For this interaction-first
  // arcade runner we turn it off, keeping small-board tool turns responsive.
  // Fable requires adaptive thinking, so it remains untouched.
  const thinkingConfig=thinkingConfigFor(selectedModel);
  const emit=event=>{try{onEvent?.(event)}catch{}};const record=(label,text,meta={})=>{const entry={label,text,...meta};traces.push(entry);emit({type:'trace',entry});};
  const tools=[
    {name:'observe_board',description:`Read the current ${kind} board as a compact text state.`,input_schema:{type:'object',properties:{}}},
    {name:'publish_update',description:'Publish a short, human-readable public checkpoint. This is not hidden reasoning: state the visible observation, immediate plan, concise reason, and expected observable result.',input_schema:{type:'object',properties:{phase:{type:'string',enum:['observe','plan','review']},observation:{type:'string'},plan:{type:'string'},reason:{type:'string'},expected:{type:'string'}},required:['phase','observation','plan','reason','expected']}},
    {name:'apply_actions',description:kind==='Klotski'?'Apply one to five legal numbered-tile slides. Every action must be an object exactly like {"id":"2","direction":"down"}; the id is the printed tile number. Include a short public reason based on visible board facts.':'Apply one to five legal actions, then observe before another batch. Include a short public reason based on visible board facts.',input_schema:{type:'object',properties:{actions:actionSchema(kind),reason:{type:'string',description:'One concise observable reason for this batch.'}},required:['actions','reason']}},
    {name:'spawn_explorer',description:'Create an isolated read-only subagent branch for one distinct question, such as deadlock risk, crate ordering, or player routing. It returns a concise report and cannot move the board.',input_schema:{type:'object',properties:{task:{type:'string'}},required:['task']}},
    {name:'write_workspace_file',description:'Write one decision-relevant private .md or .py helper artifact with real non-empty content. Do not call this with a placeholder or blank content. Python helpers may later be run only through run_workspace_python, which permits pure algorithms but blocks files, network, shell, and host access.',input_schema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:80},content:{type:'string',minLength:8,maxLength:6000}},required:['name','content']}},
    {name:'run_workspace_python',description:'Run a previously written .py helper in the restricted algorithm sandbox. It has a 2-second limit, no filesystem, network, shell, browser, environment, or key access. Use it for small map, graph, or enumeration calculations.',input_schema:{type:'object',properties:{name:{type:'string'}},required:['name']}}
  ];
  if(mode==='verify')tools.push({name:'verify_actions',description:'Check a self-proposed batch of one to five actions from the current board without changing it. It returns only legality, resulting board state, and whether that proposed batch happens to solve the board. It never searches for a route or suggests actions.',input_schema:{type:'object',properties:{actions:actionSchema(kind)},required:['actions']}});
  if(mode==='assist')tools.push({name:'run_builtin_solver',description:'Ask the local deterministic route solver for a complete verified action sequence from the current board. Use only when you explicitly want route assistance.',input_schema:{type:'object',properties:{}}});
  const modeInstruction=mode==='free'?'Run style: Free agent. No route solver or action checker is available. Derive strategy from the board yourself.':mode==='verify'?'Run style: Action checker. You may test a batch you proposed using verify_actions before applying it. The checker never searches for or reveals a route.':'Run style: Solver aid. run_builtin_solver is available only if you explicitly request a local deterministic route; it is not an explorer or your own reasoning.';
  const messages=[{role:'user',content:`${task||`Solve this ${kind} puzzle.`}\n\nYou are the main agent coordinating a small, visible puzzle-solving team. Your job is to solve the authoritative board, not merely describe it.\n\nOperating rhythm:\n1. Observe the board first.\n2. Publish a public checkpoint with: what you observed, your immediate plan, why it is appropriate, and what should visibly change next. This is a concise human-facing progress note, never hidden chain-of-thought.\n3. On a nontrivial board, begin with at most one targeted explorer question. Add a second or third explorer only if it answers a genuinely different question or resolves a conflict. Do not wait for every explorer before making an already-safe first action.\n4. You may write and run a small restricted Python helper when a graph, invariant, or small enumeration would clarify a decision. Write real content once, run it, use the output, and continue. Never submit a blank helper or mechanically retry a helper error. The helper has no route-solver access and cannot access the host.\n5. Commit at most five legal actions, each with one concise observable Reason. Re-observe after every batch or irreversible push.\n\n${modeInstruction}\nDo not output private reasoning as text. Use the tools and structured public checkpoints until solved or until you can state a concrete blocker.`}];
  for(let turn=0;turn<48;turn++){
    const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:selectedModel,max_tokens:280,system:`You control a safe, isolated ${kind} workspace. Use one or more tools in every turn; do not answer with text-only commentary. Keep the public trace readable: use publish_update for Observation / Plan / Reason / Expected, and use apply_actions.reason for a specific visible justification. Do not narrate private chain-of-thought, raw coordinate bookkeeping, or tool mechanics in text. Explorers are optional focused branches, not a required ritual: start with one only when it materially helps, then act on clear information. A helper must contain real code and directly inform the next decision.`,tools,messages,...thinkingConfig})});
    const body=await response.json();usage=addUsage(usage,usageFrom(body));emit({type:'usage',usage:usageSummary(selectedModel,usage)});if(!response.ok)return{ok:false,error:providerError(body,response.status,selectedModel),traces,explorers,usage:usageSummary(selectedModel,usage)};
    // Thinking is disabled for Sonnet/Opus interactive runs. If a model does
    // return signed thinking, preserve the original blocks unchanged for the API
    // while only public text and tool events are emitted to the browser.
    const assistantBlocks=body.content||[];
    if(assistantBlocks.length)messages.push({role:'assistant',content:assistantBlocks});const toolResults=[];
    let workspaceWritesThisTurn=0;
    for(const item of assistantBlocks){
      if(item.type==='text'){const note=publicAgentNote(item.text);if(note)record('AGENT NOTE',note);}
      if(item.type!=='tool_use')continue;let output;
      if(item.name==='observe_board'){output={board:serialise(env),actions:env.actions.length};record('OBSERVATION','Read the current board state before committing another batch.');}
      if(item.name==='publish_update'){const update={phase:String(item.input.phase||'plan'),observation:cleanPublicText(item.input.observation,220),plan:cleanPublicText(item.input.plan,220),reason:cleanPublicText(item.input.reason,220),expected:cleanPublicText(item.input.expected,220)};output={published:true};record('PLAN UPDATE',update.plan,{...update});}
      if(item.name==='apply_actions'){
        const applied=[];let failure;for(const action of(item.input.actions||[]).slice(0,5)){const result=apply(env,action);if(!result.ok){failure=result.error;break}const committed=result.action||action;applied.push(committed);emit({type:'action',action:committed, index:env.actions.length, board:result.board});if(result.solved)break;}
        const reason=cleanPublicText(item.input.reason||'The next short batch follows the current board strategy.',240),actions=applied.map(action=>prettyAction(kind,action));record('ACTION PLAN',`Committed ${actions.length} legal action${actions.length===1?'':'s'}.`,{reason,actions,failure:failure||null});output={ok:applied.length>0,actions:applied,failure:failure||null,board:serialise(env),solved:isSolved(env)};
      }
      if(item.name==='verify_actions'){
        const candidate=structuredClone(env),checked=[];let failure;
        for(const action of(item.input.actions||[]).slice(0,5)){const result=apply(candidate,action);if(!result.ok){failure=result.error;break}checked.push(result.action||action);if(result.solved)break;}
        output={legal:!failure,actions:checked,failure:failure||null,board:serialise(candidate),solved:isSolved(candidate)};
        record('ACTION CHECK',failure?`Rejected the proposed batch after ${checked.length} legal action${checked.length===1?'':'s'}: ${failure}. No route information was provided.`:`Checked ${checked.length} self-proposed action${checked.length===1?'':'s'}: legal. No route information was provided.`);
      }
      if(item.name==='run_builtin_solver'){const plan=solve(structuredClone(env));output={found:plan!==null,plan};record('SOLVER AID',plan!==null?`Local route solver returned a ${plan.length}-action completion route at the agent’s request.`:'Local route solver found no safe completion route from this state.');}
      if(item.name==='spawn_explorer'){const objective=cleanPublicText(item.input.task,240);if(explorers.length>=MAX_EXPLORERS){output={ok:false,error:`Explorer limit reached (${MAX_EXPLORERS}). Compare the reports already available, then continue from the board.`};record('EXPLORER LIMIT',`The run has reached its ${MAX_EXPLORERS}-explorer branch limit; the main agent must now use its reports.`);}else{const name=`Explorer ${explorers.length+1}`;record('BRANCH START',`${name} is checking a distinct approach.`,{explorer:name,objective});const result=await runAnthropicExplorer(key,serialise(env),objective,selectedModel,kind);usage=addUsage(usage,result.usage);emit({type:'usage',usage:usageSummary(selectedModel,usage)});const explorer={name,report:result.report};explorers.push(explorer);output=explorer;record('BRANCH REPORT',`${name} returned a finding.`,{explorer:name,report:cleanPublicText(result.report,420)});emit({type:'explorer',explorer});}}
      if(item.name==='write_workspace_file'){workspaceWritesThisTurn++;const content=String(item.input.content||'').trim();if(workspaceWritesThisTurn>1){output={saved:false,error:'Only one helper file may be written in a single turn. Use the earlier tool result before requesting another file.'};}else if(content.length<8){blankWorkspaceWrites++;output={saved:false,error:'Helper content must contain at least eight non-whitespace characters. Do not retry a blank helper; continue with a concrete action or a complete helper.'};if(blankWorkspaceWrites===1)record('HELPER SKIPPED','A blank helper request was rejected; the agent must continue with a concrete action or complete helper.',{file:safeWorkspaceName(item.input.name),status:'blocked',output:'Blank helper content is not accepted.'});}else{const name=safeWorkspaceName(item.input.name),folder=workspaceFolder;await mkdir(folder,{recursive:true});await writeFile(join(folder,name),content.slice(0,6000),'utf8');workspaceFiles.add(name);output={saved:name,workspace:'isolated temporary run workspace'};record('HELPER FILE',`Saved ${name} in the isolated run workspace.`,{file:name,language:name.endsWith('.py')?'Python':'Markdown'});}}
      if(item.name==='run_workspace_python'){const name=safeWorkspaceName(item.input.name,'helper.py');if(!name.endsWith('.py')||!workspaceFiles.has(name)){output={ok:false,error:'Only a .py file written earlier in this run can be executed.'};record('HELPER RUN',`Could not run ${name}.`,{file:name,status:'blocked',output:'Only a Python file written during this run may be executed.'});}else{const result=await runWorkspacePython(workspaceFolder,name);output=result;record('HELPER RUN',result.ok?`${name} completed a restricted calculation.`:`${name} was blocked or failed.`,{file:name,status:result.ok?'complete':'failed',output:result.ok?result.output:result.error});}}
      toolResults.push({type:'tool_result',tool_use_id:item.id,content:JSON.stringify(output||{ok:false,error:'Unknown tool'})});
    }
    if(toolResults.length){idleToolTurns=0;messages.push({role:'user',content:toolResults});}
    if(isSolved(env))return{ok:true,solved:true,actions:env.actions,traces,explorers,workspace:`/private/tmp/agent-arcade-workspaces/${runId}`,usage:usageSummary(selectedModel,usage)};
    if(!assistantBlocks.length)return{ok:false,solved:false,error:'The provider returned an empty assistant turn. The visible board remains unchanged.',traces,explorers,usage:usageSummary(selectedModel,usage)};
    if(!toolResults.length){idleToolTurns++;if(idleToolTurns>=2)return{ok:false,solved:false,error:'The agent paused twice without selecting a tool. The visible board remains at its last committed state.',traces,explorers,usage:usageSummary(selectedModel,usage)};record('REPLAN','The agent did not select a tool, so it is being asked once more for an observation or short action batch.');messages.push({role:'user',content:`The board is not solved. Continue with an observation, ${mode==='verify'?'self-proposed action check, ':mode==='assist'?'optional solver aid, ':''}or short action batch. Do not retry blank workspace writes or create another explorer unless a new concrete question remains. Do not narrate private analysis in text.`});}
  }
  record('RUN LIMIT','The main agent reached its safety turn limit. The visible board remains at the last verified state.');return{ok:false,solved:false,error:'The model reached the safety turn limit before solving. The visible board remains at the last verified state.',traces,explorers,usage:usageSummary(selectedModel,usage)};
}
function runAnthropicSokobanAgent({map,model,onEvent,task,solverMode}){const env=parseSokoban(map);return runAnthropicStructuredAgent({kind:'Sokoban',env,serialise:serialiseSokoban,apply:applySokoban,solve:solveSokoban,isSolved:state=>state.goals.every(goal=>crateIndex(state,...goal)>=0),model,onEvent,task,solverMode});}
function runAnthropicMazeAgent({map,model,onEvent,task,solverMode}){const env=parseMaze(map);return runAnthropicStructuredAgent({kind:'Maze',env,serialise:serialiseMaze,apply:applyMaze,solve:solveMaze,isSolved:state=>cellKey(...state.player)===cellKey(...state.goal),model,onEvent,task,solverMode});}
const mousePoint=(value,width,height)=>{const x=Number(value?.x),y=Number(value?.y);return Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&x<=width&&y>=0&&y<=height?{x,y}:null;};
function visualKlotskiSolved(env){const target=env.pieces.find(piece=>piece.target);return Boolean(target&&target.y===env.exitRow&&target.x===env.cols-target.w)}
function serialiseVisualKlotski(env){const pieces=env.pieces.map((piece,index)=>{const tone=piece.tone||['gold','coral','mint','violet'][index%4],shape=piece.w>piece.h?`horizontal ${piece.w}-cell block`:`vertical ${piece.h}-cell block`;return`${tone} ${shape}: center (${(piece.x+piece.w/2)*100}, ${(piece.y+piece.h/2)*100})`}).join('; ');return`Virtual screen: ${env.cols*100} × ${env.rows*100}. Board coordinates begin at the top-left. Exit: right edge of row ${env.exitRow+1}. Visible pieces: ${pieces}. Cursor: (${env.cursor.x}, ${env.cursor.y}). Use mouse_drag from inside a coloured block to a destination along its long axis.`;}
function visualKlotskiPieceAt(env,point){const x=Math.floor(point.x/100),y=Math.floor(point.y/100);return env.pieces.find(piece=>x>=piece.x&&x<piece.x+piece.w&&y>=piece.y&&y<piece.y+piece.h)}
function applyVisualKlotskiDrag(env,input){const width=env.cols*100,height=env.rows*100,from=mousePoint(input?.from,width,height),to=mousePoint(input?.to,width,height);if(!from||!to)return{ok:false,error:'Mouse coordinates must be inside the virtual Klotski board.'};const piece=visualKlotskiPieceAt(env,from);if(!piece)return{ok:false,error:'The cursor must start on a visible block.'};const dx=to.x-from.x,dy=to.y-from.y,axis=Math.abs(dx)>=Math.abs(dy)?'x':'y',direction=axis==='x'?(dx>=0?'right':'left'):(dy>=0?'down':'up'),distance=Math.max(Math.abs(dx),Math.abs(dy)),steps=Math.max(1,Math.min(5,Math.round(distance/100)));const horizontal=piece.w>piece.h;if((horizontal&&axis!=='x')||(!horizontal&&axis!=='y'))return{ok:false,error:'That drag is off the selected block’s long axis.'};let moved=0;for(let index=0;index<steps;index++){if(!canMoveKlotski(env,piece,direction))break;const[moveX,moveY]=directionMap[direction];piece.x+=moveX;piece.y+=moveY;moved++;}env.cursor=to;if(!moved)return{ok:false,error:'The block is blocked before that drag can begin.'};const action={type:'klotski_drag',from,to};env.actions.push(action);return{ok:true,action,moved,screen:serialiseVisualKlotski(env),solved:visualKlotskiSolved(env)};}
function jigsawGeometry(n){const trayRows=Math.ceil((n*n)/4);return{width:1000,height:Math.max(760,350+trayRows*82),board:{x:20,y:40,size:600},tray:{x:670,y:330,size:68,gap:12,cols:4}}}
function parseVisualJigsaw({pieces,tray}){const total=Number(pieces),n=Math.sqrt(total);if(!Number.isInteger(n)||n<3||n>6)throw new Error('Visual Jigsaw supports square boards from 3 × 3 through 6 × 6.');const expected=[...Array(total)].map((_,index)=>index),remaining=Array.isArray(tray)?tray.map(Number):expected;if(remaining.length!==total||new Set(remaining).size!==total||remaining.some(tile=>!Number.isInteger(tile)||tile<0||tile>=total))throw new Error('The visual jigsaw tray must contain every tile exactly once.');return{n,remaining,placed:{},cursor:{x:0,y:0},actions:[]};}
function serialiseVisualJigsaw(env){const geometry=jigsawGeometry(env.n),filled=Object.keys(env.placed).length;return`Virtual screen: ${geometry.width} × ${geometry.height}. Board rectangle: x ${geometry.board.x}–${geometry.board.x+geometry.board.size}, y ${geometry.board.y}–${geometry.board.y+geometry.board.size}, divided into ${env.n} × ${env.n} cells. Tray starts at (${geometry.tray.x}, ${geometry.tray.y}) in four columns of visible image fragments. Board: ${filled} placed, ${env.n*env.n-filled} empty. Tray: ${env.remaining.length} visible fragments. Cursor: (${env.cursor.x}, ${env.cursor.y}). Use mouse_drag from a visible tray fragment to an empty board cell; no semantic tile or cell IDs are available.`;}
function jigsawTileAt(env,point){const geometry=jigsawGeometry(env.n),tray=geometry.tray,column=Math.floor((point.x-tray.x)/(tray.size+tray.gap)),row=Math.floor((point.y-tray.y)/(tray.size+tray.gap)),withinX=(point.x-tray.x)%(tray.size+tray.gap),withinY=(point.y-tray.y)%(tray.size+tray.gap);if(column<0||column>=tray.cols||row<0||withinX>tray.size||withinY>tray.size)return null;return env.remaining[row*tray.cols+column]??null;}
function jigsawSlotAt(env,point){const geometry=jigsawGeometry(env.n),board=geometry.board;if(point.x<board.x||point.x>=board.x+board.size||point.y<board.y||point.y>=board.y+board.size)return null;const cell=board.size/env.n,column=Math.floor((point.x-board.x)/cell),row=Math.floor((point.y-board.y)/cell);return row*env.n+column;}
function applyVisualJigsawDrag(env,input){const geometry=jigsawGeometry(env.n),from=mousePoint(input?.from,geometry.width,geometry.height),to=mousePoint(input?.to,geometry.width,geometry.height);if(!from||!to)return{ok:false,error:'Mouse coordinates must be inside the virtual Jigsaw screen.'};const tile=jigsawTileAt(env,from),slot=jigsawSlotAt(env,to);if(tile===null)return{ok:false,error:'The cursor must start on a visible tray fragment.'};if(slot===null)return{ok:false,error:'The cursor must end on a board cell.'};if(env.placed[slot]!==undefined)return{ok:false,error:'That board cell is already occupied.'};env.placed[slot]=tile;env.remaining.splice(env.remaining.indexOf(tile),1);env.cursor=to;const action={type:'jigsaw_drag',from,to};env.actions.push(action);const solved=Object.keys(env.placed).length===env.n*env.n&&Object.entries(env.placed).every(([slot,piece])=>Number(slot)===piece);return{ok:true,action,screen:serialiseVisualJigsaw(env),solved};}
async function runAnthropicMouseAgent({kind,env,serialise,apply,isSolved,model,onEvent,task,frame,reference}){
  const key=keyFor('anthropic');if(!key)return{ok:false,error:'ANTHROPIC_API_KEY is not configured.'};const selectedModel=safeModel(model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL),traces=[],explorers=[];let usage={inputTokens:0,outputTokens:0},idleTurns=0;
  const emit=event=>{try{onEvent?.(event)}catch{}};const record=(label,text,meta={})=>{const entry={label,text,...meta};traces.push(entry);emit({type:'trace',entry});};const pointSchema={type:'object',properties:{x:{type:'number',minimum:0},y:{type:'number',minimum:0}},required:['x','y']};
  const tools=[
    {name:'observe_screen',description:'Read the current virtual screen layout, including board and tray bounds, visible objects, and cursor location.',input_schema:{type:'object',properties:{}}},
    {name:'publish_update',description:'Publish a concise human-facing checkpoint. State Observation, Plan, Reason, and Expected visible result; do not provide private chain-of-thought.',input_schema:{type:'object',properties:{observation:{type:'string'},plan:{type:'string'},reason:{type:'string'},expected:{type:'string'}},required:['observation','plan','reason','expected']}},
    {name:'mouse_drag',description:'Move the virtual mouse from one screen coordinate to another. Start on a visible draggable object and end at its intended destination. This is the only way to change the visual puzzle.',input_schema:{type:'object',properties:{from:pointSchema,to:pointSchema,reason:{type:'string'}},required:['from','to','reason']}},
    {name:'spawn_explorer',description:'Ask one read-only explorer a focused visual strategy question. It cannot move the cursor or board.',input_schema:{type:'object',properties:{task:{type:'string',minLength:8,maxLength:500}},required:['task']}}
  ];
  const content=[];if(reference?.data)content.push({type:'image',source:{type:'base64',media_type:'image/jpeg',data:reference.data}});if(frame&&/^[a-zA-Z0-9+/=]+$/.test(frame)&&frame.length<2_000_000)content.push({type:'image',source:{type:'base64',media_type:'image/jpeg',data:frame}});content.push({type:'text',text:`${task||`Solve this ${kind} puzzle.`}\nYou control a virtual mouse, not semantic puzzle actions. Inspect the supplied screen image and use observe_screen for the current coordinate frame. Publish a compact visible checkpoint before a meaningful drag. Use one focused explorer only if it materially helps; then act. Every board change must use mouse_drag with literal start and end coordinates. Work in short cursor actions and observe after each drag. Do not expose private chain-of-thought.`});const messages=[{role:'user',content}];
  for(let turn=0;turn<48;turn++){
    const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:selectedModel,max_tokens:260,system:`You are operating a constrained visual-computer workspace for ${kind}. Use tools every turn. Never refer to hidden object IDs or issue semantic moves: inspect and drag the cursor. Keep public updates factual and short; do not emit private reasoning, coordinate transcripts, or tool mechanics as prose.`,tools,messages,...thinkingConfigFor(selectedModel)})});
    const body=await response.json();usage=addUsage(usage,usageFrom(body));emit({type:'usage',usage:usageSummary(selectedModel,usage)});if(!response.ok)return{ok:false,error:providerError(body,response.status,selectedModel),traces,explorers,usage:usageSummary(selectedModel,usage)};const blocks=body.content||[];if(blocks.length)messages.push({role:'assistant',content:blocks});const results=[];
    for(const item of blocks){if(item.type==='text'){const note=publicAgentNote(item.text);if(note)record('AGENT NOTE',note);}if(item.type!=='tool_use')continue;let output;
      if(item.name==='observe_screen'){output={screen:serialise(env)};record('SCREEN OBSERVATION','Read the current virtual screen before the next cursor action.');}
      if(item.name==='publish_update'){const update={observation:cleanPublicText(item.input.observation,220),plan:cleanPublicText(item.input.plan,220),reason:cleanPublicText(item.input.reason,220),expected:cleanPublicText(item.input.expected,220)};output={published:true};record('PLAN UPDATE',update.plan,update);}
      if(item.name==='mouse_drag'){const result=apply(env,item.input);output=result;if(result.ok){emit({type:'action',action:result.action,index:env.actions.length});record('CURSOR DRAG','Committed one validated virtual mouse drag.',{reason:cleanPublicText(item.input.reason,240),actions:[`(${Math.round(result.action.from.x)}, ${Math.round(result.action.from.y)}) → (${Math.round(result.action.to.x)}, ${Math.round(result.action.to.y)})`],expected:result.solved?'The puzzle should now be complete.':'The controlled board should reflect this drag.'});}else record('CURSOR BLOCKED','The proposed mouse drag was rejected without changing the board.',{failure:result.error});}
      if(item.name==='spawn_explorer'){const objective=cleanPublicText(item.input.task,240);if(explorers.length>=MAX_EXPLORERS){output={ok:false,error:`Explorer limit reached (${MAX_EXPLORERS}).`};record('EXPLORER LIMIT','The visual run has reached its explorer limit.');}else{const name=`Explorer ${explorers.length+1}`;record('BRANCH START',`${name} is reviewing one visual question.`,{explorer:name,objective});const result=await runAnthropicExplorer(key,serialise(env),objective,selectedModel,kind);usage=addUsage(usage,result.usage);emit({type:'usage',usage:usageSummary(selectedModel,usage)});const explorer={name,report:result.report};explorers.push(explorer);output=explorer;record('BRANCH REPORT',`${name} returned a finding.`,{explorer:name,report:result.report});emit({type:'explorer',explorer});}}
      results.push({type:'tool_result',tool_use_id:item.id,content:JSON.stringify(output||{ok:false,error:'Unknown tool'})});
    }
    if(results.length){idleTurns=0;messages.push({role:'user',content:results});}if(isSolved(env))return{ok:true,solved:true,actions:env.actions,traces,explorers,usage:usageSummary(selectedModel,usage)};if(!blocks.length)return{ok:false,error:'The provider returned an empty assistant turn.',traces,explorers,usage:usageSummary(selectedModel,usage)};if(!results.length){idleTurns++;if(idleTurns>=2)return{ok:false,error:'The visual agent paused twice without selecting a tool.',traces,explorers,usage:usageSummary(selectedModel,usage)};record('REPLAN','The agent did not select a cursor or observation tool.');messages.push({role:'user',content:'The puzzle is not solved. Use observe_screen or make one concrete mouse_drag; do not answer with prose only.'});}
  }
  record('RUN LIMIT','The visual agent reached its safety turn limit.');return{ok:false,error:'The visual agent reached its safety turn limit before solving.',traces,explorers,usage:usageSummary(selectedModel,usage)};
}
function runAnthropicMouseKlotskiAgent({level,model,onEvent,task,frame}){const env=parseKlotski(level);env.cursor={x:0,y:0};return runAnthropicMouseAgent({kind:'Visual Klotski',env,serialise:serialiseVisualKlotski,apply:applyVisualKlotskiDrag,isSolved:visualKlotskiSolved,model,onEvent,task,frame});}
function runAnthropicKlotskiAgent({level,model,onEvent,task,solverMode,frame}){if(level?.control==='mouse')return runAnthropicMouseKlotskiAgent({level,model,onEvent,task,frame});const env=parseKlotski(level);return runAnthropicStructuredAgent({kind:'Klotski',env,serialise:serialiseKlotski,apply:applyKlotski,solve:solveKlotski,isSolved:visualKlotskiSolved,model,onEvent,task,solverMode});}
function runAnthropicMouseJigsawAgent({pieces,tray,reference,asset,model,onEvent,task,frame}){const env=parseVisualJigsaw({pieces,tray}),referenceImage=reference?{data:null}:null;return (async()=>{if(reference)referenceImage.data=(await readFile(jigsawAssetPath(asset))).toString('base64');return runAnthropicMouseAgent({kind:'Visual Jigsaw',env,serialise:serialiseVisualJigsaw,apply:applyVisualJigsawDrag,isSolved:state=>Object.keys(state.placed).length===state.n*state.n&&Object.entries(state.placed).every(([slot,piece])=>Number(slot)===piece),model,onEvent,task,frame,reference:referenceImage});})();}

async function runAnthropicJigsawAgent({pieces=9,reference=true,asset,model}){
  const key=keyFor('anthropic');if(!key)return{ok:false,error:'ANTHROPIC_API_KEY is not configured.'};const selectedModel=safeModel(model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL),side=Math.sqrt(pieces);let content;
  if(reference){const image=await readFile(jigsawAssetPath(asset));content=[{type:'image',source:{type:'base64',media_type:'image/jpeg',data:image.toString('base64')}},{type:'text',text:`This is the reference image for a ${side} by ${side} jigsaw. Give a concise public visual inventory and a high-level assembly approach. Mention clear visual anchors, edge regions, and a sensible first batch. Do not reveal hidden reasoning.`}];}else content=[{type:'text',text:`You are operating a ${side} by ${side} jigsaw without a reference image. Give a concise public plan for cautious visual exploration, making no claims about image content you cannot see.`}];
  const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:selectedModel,max_tokens:300,system:'You are a visual jigsaw subagent. Produce only a short, public-facing observation and assembly approach.',messages:[{role:'user',content}]})});
  const body=await response.json(),usage=usageSummary(selectedModel,usageFrom(body));if(!response.ok)return{ok:false,error:providerError(body,response.status,selectedModel),usage};const report=body.content?.map(item=>item.text||'').join('').trim()||'Visual response received.';
  if(!reference)return{ok:true,reference,report,actions:[],batches:[],usage,traces:[{label:'VISION MODE',text:'Reference withheld; no image was supplied to the visual agent.'},{label:'NEXT STEP',text:report}]};
  const actions=[...Array(pieces)].map((_,tile)=>({tile,slot:tile})),batches=[];for(let index=0;index<actions.length;index+=5){const batch=actions.slice(index,index+5),row=Math.floor(index/side)+1;batches.push({actions:batch,reason:index===0?'Reason: begin with the top edge and the strongest visual anchors identified in the reference.':`Reason: continue through row ${row}, using already placed neighbours as visual consistency checks.`});}
  return{ok:true,reference,report,actions,batches,usage,traces:[{label:'VISUAL INVENTORY',text:report},{label:'HARNESS',text:`The controlled board exposes stable tile identities, so the agent is choosing placement batches while the harness validates each virtual mouse drop.`},{label:'ASSEMBLY PLAN',text:`Prepared ${batches.length} visual batches for ${pieces} placements; each batch will be shown before it moves.`}]};
}

async function testOpenAI(model){const key=keyFor('openai');if(!key)return{ok:false,error:'OPENAI_API_KEY is not configured.'};const selectedModel=safeModel(model,process.env.OPENAI_MODEL||'gpt-5.6-terra'),response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model:selectedModel,input:'Reply with exactly: AGENT_ARCADE_OK',max_output_tokens:20})}),body=await response.json();return response.ok?{ok:true,provider:'openai',model:body.model,output:body.output_text||'Response received'}:{ok:false,provider:'openai',error:providerError(body,response.status,selectedModel)};}
async function testAnthropic(model){const key=keyFor('anthropic');if(!key)return{ok:false,error:'ANTHROPIC_API_KEY is not configured.'};const selectedModel=safeModel(model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL),response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:selectedModel,max_tokens:20,messages:[{role:'user',content:'Reply with exactly: AGENT_ARCADE_OK'}]})}),body=await response.json();return response.ok?{ok:true,provider:'anthropic',model:body.model,output:body.content?.map(item=>item.text||'').join('')||'Response received'}:{ok:false,provider:'anthropic',error:providerError(body,response.status,selectedModel)};}

const runners={sokoban:runAnthropicSokobanAgent,maze:runAnthropicMazeAgent,klotski:runAnthropicKlotskiAgent};
const port=Number(process.env.PORT||4173);
createServer(async(req,res)=>{
  if(req.url==='/api/config'){json(res,200,{openai:Boolean(keyFor('openai')),anthropic:Boolean(keyFor('anthropic'))});return;}
  if(req.url==='/api/test-provider'&&req.method==='POST'){try{const body=await readJson(req),result=body.provider==='anthropic'?await testAnthropic(body.model):await testOpenAI(body.model);json(res,result.ok?200:400,result);}catch(error){console.error(error);json(res,500,{ok:false,error:'Provider test failed. Check the local server log for details.'});}return;}
  for(const [kind,runner] of Object.entries(runners))if(req.url===`/api/agent/${kind}/stream`&&req.method==='POST'){res.writeHead(200,{'content-type':'application/x-ndjson; charset=utf-8','cache-control':'no-store','connection':'keep-alive'});const send=event=>res.write(`${JSON.stringify(event)}\n`);try{const body=await readJson(req),selectedModel=safeModel(body.model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL),solverMode=normaliseSolverMode(body.solverMode);send({type:'started',model:selectedModel,kind,solverMode,runStyle:solverModeLabel(solverMode)});const result=await runner({...body,solverMode,onEvent:send});send({type:'complete',result});}catch(error){console.error(error);send({type:'complete',result:{ok:false,solved:false,error:`The streamed ${kind} run failed. Check the local server log for details.`}});}res.end();return;}
  if(req.url==='/api/agent/jigsaw/stream'&&req.method==='POST'){res.writeHead(200,{'content-type':'application/x-ndjson; charset=utf-8','cache-control':'no-store','connection':'keep-alive'});const send=event=>res.write(`${JSON.stringify(event)}\n`);try{const body=await readJson(req),selectedModel=safeModel(body.model,process.env.ANTHROPIC_MODEL||DEFAULT_CLAUDE_MODEL);send({type:'started',model:selectedModel,kind:'jigsaw',runStyle:'Virtual mouse · visual control'});const result=await runAnthropicMouseJigsawAgent({...body,onEvent:send});send({type:'complete',result});}catch(error){console.error(error);send({type:'complete',result:{ok:false,solved:false,error:'The streamed Jigsaw run failed. Check the local server log for details.'}});}res.end();return;}
  if(req.url==='/api/agent/jigsaw'&&req.method==='POST'){try{const body=await readJson(req),result=await runAnthropicJigsawAgent(body);json(res,result.ok?200:400,result);}catch(error){console.error(error);json(res,500,{ok:false,error:'Visual agent run failed. Check the local server log for details.'});}return;}
  const requestPath=req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]);if(/(^|\/)\.env\.local(?:$|\/)/.test(requestPath)||/(^|\/)\.git(?:$|\/)/.test(requestPath)){res.writeHead(403);res.end('Forbidden');return;}const path=normalize(join(root,requestPath));if(!path.startsWith(root)){res.writeHead(403);res.end('Forbidden');return;}try{const data=await readFile(path);res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found');}
}).listen(port,()=>console.log(`Agent Arcade → http://127.0.0.1:${port}`));
